### ISSUE TITLE
crash on join of a pc player

### ISSUE THREAD

**Issue by caspervanneck123** [BigBrotherTeam/BigBrother#1]
CRITICAL> Error: "Call to a member function getUniqueId() on null" (EXCEPTION) in "/plugins/phar_BigBrother-master (4)_9y5O9ha9qxlkrdh.phar/src/shoghicp/BigBrother/network/translation/Translator_101" at line 987
[Tesseract] [14:56:02] EMERGENCY> An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Tesseract] [14:56:02] EMERGENCY> Please upload the "C:\Users\Wesle\Downloads\BigBrother-master (4)\BigBrother-master\crashdumps/CrashDump_Sat_Feb_18-14.56.02-GMT_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you

**Comment by caspervanneck123** [comment]
@hmy2001 can it be fixt ?

**Comment by hmy2001** [comment]
BigBrother is new Version?

**Comment by SuperMaXAleX** [comment]
@caspervanneck123 I'm using the last version and I don't have any problems.

**Comment by caspervanneck** [comment]
@hmy2001 its stil on de new version
