### ISSUE TITLE
Login timeout

### ISSUE THREAD

**Issue by caspervanneck** [BigBrotherTeam/BigBrother#10]
@hmy2001 its not working on de latest commit 

I test it with no plugins

**Comment by Driesboy** [comment]
its timeout

**Comment by caspervanneck** [comment]
Is it working for you @Driesboy ?

**Comment by iTCMega** [comment]
yup timeout

**Comment by SuperMaXAleX** [comment]
Fixed !

**Comment by caspervanneck** [comment]
@SuperMaXAleX its not fixt

**Comment by caspervanneck** [comment]
still not working

**Comment by SuperMaXAleX** [comment]
So it's coming from one of your plugin or your world.
