### ISSUE TITLE
Install section in README.md

### ISSUE THREAD

**Issue by codexp** [BigBrotherTeam/BigBrother#100]
please add "how to install" section in README.

I can't figure out how to use this plugin.

**Comment by Icey-girl** [comment]
Drob it by plugins

**Comment by Icey-girl** [comment]
Like any other plugin

**Comment by codexp** [comment]
right, I've been looking for a plugins folder before and did not find one, should I create one?

and where should that be? 
inside `~/.minecraft` folder or somewhere else?

**Comment by codexp** [comment]
argh, I've figured it out.
I've dropped it into plugins folder of **PocketMine-MP**, started the server and ran `plugins` command, but there were 0 plugins loaded.

I've looked it up and learned that plugins have to be in .phar format, so how do I compile it to phar?

**Comment by Icey-girl** [comment]
Devtools

**Comment by codexp** [comment]
yes
