### ISSUE TITLE
Inventories it's implemented or not?

### ISSUE THREAD

**Issue by NycuRO** [BigBrotherTeam/BigBrother#101]
In readme say yes, in todo no.

It's implemented or not? 🥇 

P.s. good work with them , sounds so good! <3

**Comment by hmy2001** [comment]
Sorry, It is written as implemented but incomplete.
Dragging and shortcuts are not implemented.
Did you use that one?

**Comment by NycuRO** [comment]
Not really, i want use, but i have a factions server so it's useless..

**Comment by NycuRO** [comment]
I need inventory , crafting working for use them in production.
