### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by NycuRO** [BigBrotherTeam/BigBrother#104]
Hello.

I want help to develop this project.

Have you any link about packets of PC and them encode and decode?

I can help and with particles and sound, can you give me one link for documentation? :)

I'm free much time and i want help this project to be greatful. @hmy2001

**Comment by ProCOmpTEAM** [comment]
@NycuRO 

> Have you any link about packets of PC and them encode and decode?

http://wiki.vg/Protocol

**Comment by NycuRO** [comment]
Thanks.

What about sounds and particles?

**Comment by hmy2001** [comment]
http://wiki.vg/Protocol#Particle
http://wiki.vg/Protocol#Named_Sound_Effect

**Comment by NycuRO** [comment]
Thanks

**Comment by NycuRO** [comment]
Hello @hmy2001 . I have another question.

It's a problem if i port this plugin to NukkitX?
