### ISSUE TITLE
Frames and air

### ISSUE THREAD

**Issue by ProCOmpTEAM** [BigBrotherTeam/BigBrother#107]
setBlock() do not delete frames, and by hand this can not delete. MCPE players do not see it. 
![default](https://user-images.githubusercontent.com/24737193/35727042-e7127802-0817-11e8-8797-774a6199126b.png)

**Comment by eternalharvest** [comment]
Sorry, I'm currently not enough time to confirm this issue and fix this problem.
But I think I can fix it, just listen the `BlockUpdateEvent` and implement the code which handle the event.
Or I think you can avoid this issue by calling `Level#setBlock()` with `direct = true`.

**Comment by hmy2001** [comment]
I think i fixed it
