### ISSUE TITLE
Login timeout after last updates

### ISSUE THREAD

**Issue by ProCOmpTEAM** [BigBrotherTeam/BigBrother#111]
I written that has the connection earlier, now i have Login timeout from all of accounts. It is over! This nicknames have not online mode  . TLauncher

![default](https://user-images.githubusercontent.com/24737193/37393678-cc176bae-2782-11e8-8c24-a03a954cbb1c.png)

**Comment by ProCOmpTEAM** [comment]
Today i update my BigBrother after version #110 and now i get's this timeouts

**Comment by caspervanneck** [comment]
are you sure you are using latest pmmp

**Comment by caspervanneck** [comment]
@ProCOmpTEAM

**Comment by caspervanneck** [comment]
are you sure that your using latest pmmp

**Comment by ProCOmpTEAM** [comment]
@caspervanneck thanks for help, now i have not timeout error
