### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by 7kasper** [BigBrotherTeam/BigBrother#119]
Hello guys. It's amazing what you are doing but I wonder, why?
Letting PC and PE players has long been a dream, but why base it on PMMP instead of Spigot? À la the other way around. I think spigot (or even glowstone) will provide more stability for this kind of project.

**Comment by robske110** [comment]
Because relying on pmmp to do the mcpe network side of things is much easier. The MCPC protocol is rather ‘stable’ compared to the MCBE protocol bullshit.

**Comment by Remu-2018** [comment]
@robske110 never heart about pspe its already better then pmmp and bigbrother 7kasper is one of the dev of it he is amazing (:

**Comment by eternalharvest** [comment]
@7kasper

This project was originally started by Shoghicp Cervantes who is original author of PMMP.
So, historically it was natural to implement BigBrother as a plugin of PMMP.

We had considered about implementing BigBrother as server neutral protocol translation gateway.
But BigBrother strongly depends on PMMP API and internal data.
So, we concluded that it is difficult to do so.

And we also don't like the PHP language though BigBrother was written in PHP. But if we decided to use another server other than PMMP, we must make big effort to port it.
And we must consider about whether if this BigBrother project continues or abort. It would be a Big decision, so we must consider well.

We still looking for a solution which makes BigBrother better and we still continuing this project.

**Comment by 7kasper** [comment]
Yeah I understand. I just remembered you guys and was amazed you were still going. Well as Remu said I am working with 2 others (Shevchik and MrPowerGamerBR) on the other side (letting PE join bukkit servers). We are quite far but its still a long way. Its worth checking it out sometime, you can find most info on our discord. Perhaps you can give us tips ans since we're colleagues, both in the proto business feel free to ask me if you need help with the protocol! My discord: 7kasper#0325
