### ISSUE TITLE
How I make it into phar so i can use it on my server?

### ISSUE THREAD

**Issue by NormalOcean6686** [BigBrotherTeam/BigBrother#122]
### Issue description

How I make it into phar so i can use it on my server? btw thx for the greatest plugin ever

**Comment by sk665030** [comment]
You dont need to make it as .phar you can use dev tools for the same to run on your pc
Just search for DevTools on Poggit.

**Comment by NormalOcean6686** [comment]
Um.. Already tried before posting that comment

**Comment by sk665030** [comment]
Which version of pocketmine are you using?

**Comment by sk665030** [comment]
Or could you tell me what error you got while using DevTools

**Comment by NormalOcean6686** [comment]
I think it is the newest version

**Comment by NormalOcean6686** [comment]
Also does this plugin work with te newest update

**Comment by TGC-TECH** [comment]
Here. Extract the zip and you will have a compiled version.  Enjoy! 
[BigBrother_v1.6.0.zip](https://github.com/BigBrotherTeam/BigBrother/files/2178075/BigBrother_v1.6.0.zip)
It is really not hard to compile with dev tools. and  if you can't do that you are likely not capable of dealing with the relatively high number of issues in this software but feel free to give it a try
