### ISSUE TITLE
you can copy items with chest

### ISSUE THREAD

**Issue by djdisodo** [BigBrotherTeam/BigBrother#124]
### Issue description
you can copy items with chest
it's a big issue for economy servers

### Prerequisite
gamemode is survival
logged in with pc

### How to reproduce
first. place a chest
second. put item into chest with Shift + right click
third. bring back the item in the chest without closing chest

item is copied

### Server log(crash dump)

no errors

**Comment by sk665030** [comment]
Please elaborate like what version of pocketmine,BigBrother plugin,php,are you using?

**Comment by djdisodo** [comment]
@sk665030 
[14:32:53] [Server thread/INFO]: This server is running PocketMine-MP 1.7dev-1136 「[REDACTED]」 implementing API version 3.0.0-ALPHA12 for Minecraft: PE v1.4.0 (protocol version 261)

bigbrother: https://github.com/BigBrotherTeam/BigBrother/tree/24e687cddb5e1bdb8f73f93d0e4903de4524d767
(lastest)

**Comment by sk665030** [comment]
Give me the link for your pocketmine,phar also so that I can reproduce the
same
-Thank You

**Comment by djdisodo** [comment]
[PocketMine-MP.zip](https://github.com/BigBrotherTeam/BigBrother/files/2101346/PocketMine-MP.zip)

@sk665030

**Comment by sk665030** [comment]
You have provided with plugin and phar
Also provide source code and screenshot of the directory of your pocketmine
to know where you place files and what version of DevTools are you using.
It will be fine if you upload whole directory so that I can give it a try
-Thank You

**Comment by hmy2001** [comment]
It is not implemented yet.
