### ISSUE TITLE
Need link for latest pmmp,bigbrother plugin,phar and php

### ISSUE THREAD

**Issue by sk665030** [BigBrotherTeam/BigBrother#125]
### Issue description

I need the link to latest version of pmmp,phar and php I'm getting a lot errors and always crash my pmmp
Thanks in Advance @hmy2001 I'll wait for your answer

**Comment by djdisodo** [comment]
[pmmp](https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/artifact/PocketMine-MP.phar)

u can use devtools with bigbrother source


[php-linux](https://jenkins.pmmp.io/job/PHP-7.2-Linux-x86_64/lastSuccessfulBuild/artifact/PHP_Linux-x86_64.tar.gz)
[php-windows](https://jenkins.pmmp.io/job/PHP-7.2-Aggregate/lastSuccessfulBuild/artifact/PHP-7.2-Windows-x64.zip)

**Comment by sk665030** [comment]
Thanks for your help I set everything Up!!
Phar from Jenkins,Php and source from pmmp
