### ISSUE TITLE
Will this plugin be updated  to mcpc 1.13

### ISSUE THREAD

**Issue by NormalOcean6686** [BigBrotherTeam/BigBrother#126]
### Issue description
Will this plugin be updated  to mcpc 1.13

**Comment by NormalOcean6686** [comment]
PLus i love this plugin it is my favourite plugin ever

**Comment by Wesley-VanNeck** [comment]
@NormalOcean6686 probably not there arnt any fixes for a long time

**Comment by Wesley-VanNeck** [comment]
Only pe protocol changes

**Comment by eternalharvest** [comment]
@NormalOcean6686, @InsaneLegacy 

Thanks to hmy2001's work, we create new branch `1.13.2` and `1.14.4` to manage code related to newer version of protocol. You can download latest build from bintray, please refer to the last section of README.md.
