### ISSUE TITLE
tread crash ?

### ISSUE THREAD

**Issue by caspervanneck** [BigBrotherTeam/BigBrother#13]
[Server thread/CRITICAL]: [Network] Stopped interface shoghicp\BigBrother\network\ProtocolInterface due to Undefined class constant 'ACTION_RESPAWN'
[14:46:23] [Server thread/EMERGENCY]: [ServerThread #6716] ServerThread crashed!

**Comment by SuperMaXAleX** [comment]
If you are using BlueLight, don't use it.

**Comment by caspervanneck** [comment]
ok i know alread how t o fix it @SuperMaXAleX
