### ISSUE TITLE
Compatible versions of PMMP?

### ISSUE THREAD

**Issue by jasongabler** [BigBrotherTeam/BigBrother#132]
I can never seem to get a version of PocketMine-MP and BigBrother that work together. I aways get some variation of:

[Server thread/ERROR]: Could not load plugin 'BigBrother': Incompatible API version (plugin requires one of: x.y.z)

I've also seen this error message saying it "requires one of: 1.10.0" and yet I am running "Bedrock Edition server version v1.10.0". Am I not understand what the error message is referring to?

The current version of PMMP for the default install is 3.7.0 which uses Bedrock 1.10.0.  I haven't been able to find anything, including any fork of PMMP, which has the 1.12.2 Bedrock version that the BigBrother repo's README says it requires.

If would be very helpful if the release notes included precise suggestions or even links for the PMMP executable that works the given BigBrother release. 

Thanks for your hard work. Looking forward to figuring out how to enjoy it!

**Comment by Satella1012** [comment]
Its dead so dont even bother

**Comment by DenielWorld** [comment]
how does this work? I've installed it, but entering the ip on pc sends me to a different server.

**Comment by hmy2001** [comment]
Yes. compatible.
