### ISSUE TITLE
Issue with the port binding to the specified IP address.

### ISSUE THREAD

**Issue by KingRainbow44** [BigBrotherTeam/BigBrother#138]
### Issue description
The plugin disables itself after it binds the port. I feel like its an issue with the port I assigned 85681.

### Prerequisite
DevTools, The Phar

### How to reproduce
Run the plugin on a host like Ramshard and use the port 85681.

### Server log(crash dump)
17.06 04:10:24 [Server] Server thread/INFO Enabling WitherProxy v1.11.3
17.06 04:10:24 [Server] Server thread/INFO OS: Linux 24e4315d012f 4.9.177-xxxx-std-ipv6-64 #721950 SMP Fri May 17 08:31:25 UTC 2019 x86_64
17.06 04:10:24 [Server] Server thread/INFO PHP version: 7.2.8
17.06 04:10:24 [Server] Server thread/INFO PMMP Server version: v1.11.0
17.06 04:10:24 [Server] Server thread/INFO PMMP API version: 3.8.4
17.06 04:10:24 [Server] Server thread/INFO Use openssl as AES encryption engine.
17.06 04:10:24 [Server] Server thread/INFO Use openssl as RSA encryption engine.
17.06 04:10:24 [Server] Server thread/INFO OpenSSL Library version: OpenSSL 1.1.0h  27 Mar 2018
17.06 04:10:24 [Server] Server thread/INFO OpenSSL Header version: OpenSSL 1.1.0h  27 Mar 2018
17.06 04:10:24 [Server] Server thread/INFO OpenSSL Library version: OpenSSL 1.1.0h  27 Mar 2018
17.06 04:10:24 [Server] Server thread/INFO OpenSSL Header version: OpenSSL 1.1.0h  27 Mar 2018
17.06 04:10:24 [Server] Server thread/INFO Server is being started in the background
17.06 04:10:24 [Server] Server thread/INFO Generating keypair
17.06 04:10:24 [Server] Server thread/INFO Starting Minecraft: PC server on 188.165.173.121:85681 version 1.12.2
17.06 04:10:24 [Server] Server thread/CRITICAL Exception: "Invalid port range" (EXCEPTION) in "plugins/WitherProxy_v1.11.3.phar/src/shoghicp/BigBrother/network/ServerThread" at line 74
17.06 04:10:24 [Server] Server thread/DEBUG #0 plugins/WitherProxy_v1.11.3.phar/src/shoghicp/BigBrother/network/ProtocolInterface(109): shoghicp\BigBrother\network\ServerThread->__construct(object pocketmine\utils\MainLogger, object BaseClassLoader, integer 85681, string[15] 188.165.173.121, string[111] ..bPocketMine-MP server using ..6..lBigBrother..r..b plugin...aConnect to Minecr, string[86] /plugin_data/WitherProxy/server-ic, boolean )
17.06 04:10:24 [Server] Server thread/DEBUG #1 plugins/WitherProxy_v1.11.3.phar/src/shoghicp/BigBrother/BigBrother(184): shoghicp\BigBrother\network\ProtocolInterface->__construct(object shoghicp\BigBrother\BigBrother, object pocketmine\Server, object shoghicp\BigBrother\network\Translator, integer 256)
17.06 04:10:24 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginBase(123): shoghicp\BigBrother\BigBrother->onEnable()
17.06 04:10:24 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(588): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
17.06 04:10:24 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1992): pocketmine\plugin\PluginManager->enablePlugin(object shoghicp\BigBrother\BigBrother)
17.06 04:10:24 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1978): pocketmine\Server->enablePlugin(object shoghicp\BigBrother\BigBrother)
17.06 04:10:24 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1718): pocketmine\Server->enablePlugins(integer 0)
17.06 04:10:24 [Server] Server thread/DEBUG #7 src/pocketmine/PocketMine(266): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /, string[55] /plugins/)
17.06 04:10:24 [Server] Server thread/DEBUG #8 (1): require(string[114] phar:///PMMP-1.11.0-Latest-Stable.)
17.06 04:10:24 [Server] Server thread/INFO Disabling WitherProxy v1.11.3

**Comment by eternalharvest** [comment]
@KingRainbow44 

I think this is not  BigBirother issue, it is a specification of OS u are using.
Port number 85681 is not a valid range of ip protocol (1-65535).
Why are u trying to assign the port number other than default (25565)?

**Comment by KingRainbow44** [comment]
@eternalharvest 

17.06 14:37:41 [Server] Server thread/INFO Starting Minecraft: PC server on 188.165.173.121:65535 version 1.12.2
17.06 14:37:41 [Server] Server thread/INFO Enabling ShadowAntiCheat v3.6.5
17.06 14:37:41 [Server] INFO Warning: stream_socket_server(): unable to connect to tcp://188.165.173.121:65535 (Cannot assign requested address) in phar:///plugins/WitherProxy_v1.11.3.phar/src/shoghicp/BigBrother/network/ServerManager.php on line 146
17.06 14:37:41 [Server] ServerThread thread/CRITICAL **** FAILED TO BIND TO 188.165.173.121:65535!
17.06 14:37:41 [Server] ServerThread thread/CRITICAL Perhaps a server is already running on that port?

The server log provided above is part of the reason I was using 85681. Ports won't bind on the respective  IP provided in the config file.

**Comment by eternalharvest** [comment]
@KingRainbow44

I understand why u are not using default port number and the intent of you.
Anyway, u can't use 85681 as a port number for BigBrother listening ip address because it is not valid port number.

In linux os (almost all os is same though), you must use port in range 1 - 65535, and if you have no root privileges, you must use port number more than 1024.
Please clarify what is the issue, this issue just describing the result u don't wish.

If you wish yet another config to specify the listening ip address, we may need to refactor the plugin startup routine.
If so, please change the title of this issue! so that we can solve the problem.

**Comment by KingRainbow44** [comment]
I have changed the title of the issue to the current issue. I would love another config for the listening IP address.

**Comment by eternalharvest** [comment]
I have never used RAMShared service, so i'm not sure about the limitation.

It seems there is `interface` option in the BigBrother config.
I think u can listen specific ip address and port number.

https://github.com/BigBrotherTeam/BigBrother/blob/master/resources/config.yml#L4

I think we don't need to refactor the code.
Just configure it properly.

**Comment by KingRainbow44** [comment]
I have already changed the interface option in the config. If I change it back to 0.0.0.0, the port binds but you can not connect to the server.

**Comment by eternalharvest** [comment]
It seems, ramshared support extra port for user (ramshared support staff taught me via chat).
But I'm not a user of ramshared, and i'm not sure which service plan u have contracted.
port.
I think it would be better if @KingRainbow44 ask ramshared support directly!

**Comment by KingRainbow44** [comment]
Thanks for this @eternalharvest, I will try and contact them today.

**Comment by eternalharvest** [comment]
@KingRainbow44 
Any update on this?

Why are u using ur own fork of this Project?
Why u forked this project without any git history??
It is difficult to compare the source.

And we only support our latest master branch.
And this is not a support forum, this project is maintained by volunteer contributors.

**Comment by KingRainbow44** [comment]
Sorry for leaving no updates. I have been trying to resolve this issue. I'm not using my fork on the project. I am using the BigBrotherTeam repo. The issue still resides. It is not binding. I believe that the host is blocking the IP. I will just close it here for now. Thank you for your help @eternalharvest. I might re-open the issue if something else happens.

**Comment by KingRainbow44** [comment]
New Information! I'm switching hosts to see if this problem persists. If anything is found, I will reopen this issue!

**Comment by KingRainbow44** [comment]
Yes! This has been figured out! The port was not binding because the port wasn't open. Yeah, it was simple.
