### ISSUE TITLE
Can't eat placed cake block by PC users

### ISSUE THREAD

**Issue by eternalharvest** [BigBrotherTeam/BigBrother#144]
### Issue description
When I was playing MCPC (Java), I noticed that I can't eat placed Cake block.

But when I play in same world with MCBE, I can eat placed Cake.
When I observe this scenario by PC users, it seems nothing happen (block is not updated).

### Prerequisite
* OS: Linux garnet 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64
* PHP version: 7.2.19
* PMMP Server version: v1.11.0
* PMMP API version: 3.8.4
* BigBrother revision: 1.6.0-dev-244-gccb52c7

### How to reproduce
1. Place a Cake Block
2. Right click placed Cake block

### Server log(crash dump)
not available

**Comment by hmy2001** [comment]
I cannot reproduce this issue.

**Comment by eternalharvest** [comment]
sorry, it's because my misunderstanding...
i'm not hungry!
