### ISSUE TITLE
Skin parts such as Jacket, Sleeve, Pants are not visible by Desktop Players

### ISSUE THREAD

**Issue by eternalharvest** [BigBrotherTeam/BigBrother#148]
### Issue description
As the title says, desktop player can't see skin parts sucha as Jacket, Sleeve, Pants.
So, desktop player is NAKED!
it is too embarrassed !!!

### Prerequisite
* OS: Linux garnet 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64
* PHP version: 7.2.19
* PMMP Server version: v1.11.0
* PMMP API version: 3.8.5
* BigBrother revision: 1.6.0-dev-255-g200f5ae

### How to reproduce
* Upload skin which contains parts
* Try to login with MCPC Java version

### Server log(crash dump)
* N/A

**Comment by hmy2001** [comment]
https://wiki.vg/Protocol#Client_Settings
https://wiki.vg/Entity_metadata#Player
We must enable flag
