### ISSUE TITLE
Colors Codes don't fully work.

### ISSUE THREAD

**Issue by Driesboy** [BigBrotherTeam/BigBrother#16]
in popup
sendpopup("§bhi") and /n dont work in popup

**Comment by SuperMaXAleX** [comment]
Color codes are working, but the associated packet isn't fully implanted.

**Comment by hmy2001** [comment]
fixed it by https://github.com/BigBrotherTeam/BigBrother/commit/b59f6c523368dda741c8738a159840f71a04b71f and    
https://github.com/BigBrotherTeam/BigBrother/commit/b59f6c523368dda741c8738a159840f71a04b71f
