### ISSUE TITLE
[Server thread/INFO]: 正在启用插件 BigBrother v1.6.0-beta [13:15:29] [Server thread/CRITICAL]: [BigBrother] Couldn't find a protocol translator for #389, disabling plugin

### ISSUE THREAD

**Issue by TanShould** [BigBrotherTeam/BigBrother#160]
### Issue description

[Server thread/INFO]: 正在启用插件 BigBrother v1.6.0-beta
[13:15:29] [Server thread/CRITICAL]: [BigBrother] Couldn't find a protocol translator for #389, disabling plugin

**Comment by KingRainbow44** [comment]
You're using an outdated version of BigBrother.

**Comment by strich3** [comment]
Bro 1.14.60

xD

**Comment by strich3** [comment]
I will fix it! xD
