### ISSUE TITLE
Crash #3 yey

### ISSUE THREAD

**Issue by strich3** [BigBrotherTeam/BigBrother#165]
PocketMine-MP Crash Dump Wed May 13 14:51:26 UTC 2020

Error: Call to undefined method shoghicp\BigBrother\utils\ConvertUtils::convertBlockEntity()
File: plugins/BigBrother-v1.5.0-beta-610-ge6c8936/src/shoghicp/BigBrother/network/protocol/Play/Server/ChunkDataPacket
Line: 71
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BigBrother v1.6.0-beta

Code:

Backtrace:
#0 plugins/BigBrother-v1.5.0-beta-610-ge6c8936/src/shoghicp/BigBrother/network/Packet(239): shoghicp\BigBrother\network\protocol\Play\Server\ChunkDataPacket->encode()
#1 plugins/BigBrother-v1.5.0-beta-610-ge6c8936/src/shoghicp/BigBrother/network/ProtocolInterface(185): shoghicp\BigBrother\network\Packet->write()
#2 plugins/BigBrother-v1.5.0-beta-610-ge6c8936/src/shoghicp/BigBrother/network/ProtocolInterface(243): shoghicp\BigBrother\network\ProtocolInterface->sendPacket(integer 6, object shoghicp\BigBrother\network\protocol\Play\Server\ChunkDataPacket)
#3 src/pocketmine/Player(3166): shoghicp\BigBrother\network\ProtocolInterface->putPacket(object shoghicp\BigBrother\DesktopPlayer, object shoghicp\BigBrother\network\protocol\Play\Server\ChunkDataPacket, boolean , boolean )
#4 src/pocketmine/Player(3183): pocketmine\Player->sendDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket, boolean , boolean )
#5 src/pocketmine/Player(972): pocketmine\Player->dataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
#6 plugins/BigBrother-v1.5.0-beta-610-ge6c8936/src/shoghicp/BigBrother/DesktopPlayer(385): pocketmine\Player->sendChunk(integer 12, integer 11, object pocketmine\network\mcpe\protocol\BatchPacket)
#7 src/pocketmine/level/Level(2489): shoghicp\BigBrother\DesktopPlayer->sendChunk(integer 12, integer 11, object pocketmine\network\mcpe\protocol\BatchPacket)
#8 src/pocketmine/level/Level(2544): pocketmine\level\Level->sendChunkFromCache(integer 12, integer 11)
#9 src/pocketmine/level/format/io/ChunkRequestTask(81): pocketmine\level\Level->chunkRequestCallback(integer 12, integer 11, object pocketmine\network\mcpe\protocol\BatchPacket)
#10 src/pocketmine/scheduler/AsyncPool(304): pocketmine\level\format\io\ChunkRequestTask->onCompletion(object pocketmine\Server)
#11 src/pocketmine/Server(2384): pocketmine\scheduler\AsyncPool->collectTasks()
#12 src/pocketmine/Server(2143): pocketmine\Server->tick()
#13 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
#14 src/pocketmine/Server(1584): pocketmine\Server->start()
#15 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[12] /home/Lobby/, string[20] /home/Lobby/plugins/)
#16 src/pocketmine/PocketMine(296): pocketmine\server()
#17 (11): require(string[64] phar:///home/Lobby/pocketmine.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.12.0 [Protocol 390]
Git commit: 77d45bf11674a1360f58e32a14a3b09f423d860c
uname -a: Linux v2576 4.19.0-8-cloud-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64
PHP Version: 7.3.16
Zend version: 3.3.16
OS : Linux, linux

Loaded plugins:
MyStats 1.4.13 by CzechMPDevs, VixikCZ for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0
SimpleMSG 1.0.0 by tim03we for API(s) 3.0.0
SimpleTagsUI 1.0.0 by DaRealAqua for API(s) 3.6.0
CustomCommands 1.0.0 by xXUnlxgitGxmxrXx for API(s) 3.0.0, 4.0.0
SignServerStats 1.1.1 by robske_110 for API(s) 3.0.0
MapImageEngine 1.1.3 by FaigerSYS for API(s) 3.0.0
BlockParty 1.0.1_BETA by DragoVN for API(s) 3.0.0
RedstoneCircuit 2.0.0 by tedo0627 for API(s) 3.6.0
ServerLoveMCBE 1.0.0 by HBIDamian for API(s) 3.11.0
BadWordBlocker 1.2.8 by survanetwork for API(s) 3.0.0
PlayerSelectors 1.0.0 by Ad5001 for API(s) 3.0.0
BossAnnouncement 2.0.0 by XenialDan for API(s) 3.9, 4.0.0
WarpUI 3.3.1 by XenialDan for API(s) 3.11
ReportUI 1.0.0 by MasApip for API(s) 3.0.0, 4.0.0
Elevator 1.0 by ColinHDev for API(s) 3.0.0
VoteBan 1 by GmWM for API(s) 3.0.0
fireworks 1.1.0 by XenialDan for API(s) 3.9
PortalFlameWings 2 by DeadOnBushPH for API(s) 3.0.0, 4.0.0
FreundeSystem 1.1.0 by Scamnex for API(s) 3.0.0, 4.0.0
PvPLevels 1.0 by corytortoise for API(s) 2.0.0, 3.0.0-ALPHA9, 3.0.0-ALPHA11, 3.0.3, 3.1.1
SkyWars 1.2.1 by VixikHD for API(s) 3.0.0
TempBanUI 2.3 by SonsaYT for API(s) 3.0.0, 4.0.0
PerWorldInventory 1.0.0 by BlockHorizons for API(s) 3.0.0
MSpawns 2.2 by EvolSoft for API(s) 3.0.0
KDR 1.0.0 by JackMD for API(s) 3.0.0
BlockProtect 1.0.0 by DarkByx for API(s) 3.3.1, 3.3.4, 4.0.0
BetterVoting 1.5.0 by Twisted for API(s) 3.2.0
AlwaysSpawn 2.2.4 by Philip Shilling for API(s) 3.0.0
BuildUHC 1.0.0 by TheRealKizu for API(s) 3.0.0
freeze 2.1.0 by Bavfalcon9 for API(s) 3.0.0
PECollide 1.1 by saxavlax001 for API(s) 3.0.0
Wings 1 by Array for API(s) 3.0.0
VanishV2 1.6 by superbobby for API(s) 3.0.0
WarpsPro 1.3.0 by nikoskon for API(s) 3.0.0
LevelAPI 1.4.0 by Mohamed El Yousfi for API(s) 3.0.0
MultiProtocol 1.0.0 by VixikCZ for API(s) 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.1
Trampoline 1.2 by Vladu11 for API(s) 3.0.0
BedrockClans 2 by Wertzui123 for API(s) 3.0.0
LKB-NashanPlays 1.1.0 by NashanPlaysYT for API(s) 3.4.0, 3.3.0, 3.2.0, 3.1.0, 3.6.0
EC-TableUI 1.1.1-pre by  for API(s) 3.0.0
Mavoric 1.0.3 by Bavfalcon9 for API(s) 3.0.0
MCPEToDiscord 1.4.1 by JaxkDev for API(s) 3.0.0
BuilderTools 1.2.0-beta2 by CzechPMDevs, VixikCZ for API(s) 3.0.0
SignIt 1.1.0 by Wertzui123 for API(s) 3.0.0
RenameItems 1.1 by Wertzui123 for API(s) 3.0.0
PurePerms 1.4.2-c2a by 64FF00 & ProjectInfinity for API(s) 3.0.0
ScoreHud 5.1.1 by JackMD for API(s) 3.0.0
CustomFFA 1.2.3_BETA by HangitYT for API(s) 3.0.0
FormAPI 1.3.0 by jojoe77777 for API(s) 3.2.0
CPS 1.0.0 by DaPigGuy, JackMD for API(s) 3.0.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
NickUI 1 by MatzeLP for API(s) 3.0.0, 4.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0
StairSeat 1.4.0 by korado531m7 for API(s) 3.9.0
Spleef 1.0.2 by XenialDan for API(s) 3.0.0, 4.0.0
TNTRun 1.0.1 by XenialDan for API(s) 3.11
MobStacker 0.2.3 by UnknownOre for API(s) 3.8.1
AutoClearLagg 3.0.0 by Twisted for API(s) 3.0.0
NoFallDamage 1.0 by DeveloperNeb101 for API(s) 3.0.0
SkriptBE 1.0.0 by DominixZ for API(s) 3.0.0
SignShopXSOAP 666 by xSoapers for API(s) 3.0.0, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11
SizePlayer 1.1.0 by  for API(s) 3.0.0
CustomAlerts 2.1 by EvolSoft for API(s) 3.0.0
WorldProtect 2.3.8 by aliuly for API(s) 3.0.0
SignSellXSOAP 1.0.0 by xSoapers for API(s) 3.0.0, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11
CustomSetting 1.0.3 by LeNick for API(s) 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0
NoHunger 1.0.3 by Matthww for API(s) 3.0.0
ZMusicBox 3.1.0 by Zzm for API(s) 3.0.0, 4.0.0
OnlineTime 1.3 by Zedstar16 for API(s) 3.0.0
OreGen 1.1.4 by Xenophilicy for API(s) 3.0.0
MaxEnchants 1.2.0 by Xenophilicy for API(s) 3.0.0
LuckyBlock 0.0.3 by Palente for API(s) 3.0.0
JoinCommands 2.0.0 by Array for API(s) 3.0.0
AntiSpamPro 1.4.1 by awzaw for API(s) 3.0.0
BlazinJoin 1.1.5 by iiFlamiinBlaze for API(s) 3.0.0
CrashAndBan 0.1.0 by jasonwynn10 for API(s) 3.0.0
Newspaper 1.0.1 by Johnmacrocraft for API(s) 3.3.0
ChestShop 2.2.5 by MinecrafterJPN for API(s) 3.0.0
Slapper 1.5.2 by jojoe77777 for API(s) 3.9.0
PiggyShopUI 2.0.0 by DaPigGuy for API(s) 3.2.0
LobbySystem-Hyroxing 2.2.4-BETA by iTzFreeHD-Hyroxing-Dev for API(s) 3.0.0, 3.9.5, 3.11.0, 4.0.0
CrashFixer 1 by TutoGamerWalid (wiligangster) for API(s) 3.7.1
ExampleUI 1 by SaveConnectionPE for API(s) 3.0.0
TimeCommander 2.2 by Zeao for API(s) 3.0.0
Broadcaster 1.5 by EvolSoft for API(s) 3.0.0
SimpleBanner 0.0.1 by  for API(s) 3.0.0
Charm 1.0.0 by JackMD for API(s) 3.0.0
WhatCrates 2.0.0 by SchdowNVIDIA for API(s) 3.0.0
SlapperPlus 1.0.3 by jojoe77777 for API(s) 3.0.0, 4.0.0
JoinUI 1.1.0 by  for API(s) 3.0.0
Rewards 3.0 by Wertzui123 for API(s) 3.0.0
DevTools 1.14.0 by PocketMine Team for API(s) 3.11.3
Drops 1.0.0 by Shabzz102, Atomization for API(s) 3.0.0
BoostPad 1 by BrokenItZAndrei100. for API(s) 2.0.0, 3.0.0
BankNotes 2.0.3 by AndreasHGK for API(s) 3.7.0
TopVoter 3.2.0 by SalmonDE for API(s) 3.0.0
PortalsPE 1.1.1 by luca28pet for API(s) 3.0.0
Trident 1.0.0 by TheNote, CortexPE for API(s) 3.0.0, 4.0.0
Crossbow 1.0.9 by  for API(s) 3.9.0
MyPlot 1.6.13 by Wiez, Exxarion, jasonwynn10 for API(s) 3.4.0
EmeraldWarp 1.0.0 by ElementalMinecraftGaming for API(s) 3.7.1
AllAPILoader 1.0.0 by TheNewHEROBRINE, JackMD, OhhhAlex for API(s) 3.0.0
ParticlesUI 1.0.0 by Giings, xSoapers for API(s) 3.0.0
RankShopSystem 1.0.0 by zZPROGAMERZz423 | Â§eFor issues report by Â§2Visiting GitHub.com/zZPROGAMERZz423 for API(s) 3.0.0
BlockSniper 3.2.3 by BlockHorizons, Sandertv (@Sandertv), Chris-Prime (@PrimusLV) for API(s) 3.2.0
MyPlotBorders 0.1.0 by jasonwynn10 for API(s) 3.0.0
MyPlotPlotHomes 0.1.0 by jasonwynn10 for API(s) 3.0.0
BigBrother 1.6.0-beta by BigBrotherTeam for API(s) 3.7.0
BedWars 1.1.4 by Ceepkev77 for API(s) 3.0.0, 4.0.0
MultiWorld 1.6.0-beta1 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 3.12.0
InvSee 1.0.0 by BlockHorizons for API(s) 3.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtXXtz4riy/yoU59StbJ0QMM8kf2zdhJDHbjJDhcxj53grJWwBGmzLK9sEcu5+99uSX5IIwRBn
t+6t2Uew27j1az1a3a2W+E91QpmLwscFZgGhXvW0eVgNiYurp0bn+KR1bLSPu4dVBwXhgDHKqqf/
qYYrHx5X4/vDqouDAE05pY8cpxLSSuTZeEI8bFdcHM6oXQlmdDojlm+a52R6zmg4w8w0o5A4gWn2
qQeFh5/43empFd+dO9SaD7yQhKuDn6CQSeQ4l8ThpdRn1MX1Wzoer+q+E02JF9RztrWFcdQ5atTG
OES1rtGoTXHXAkG69YBZ9RSI9ELdw+ETZfO6D/fUok596KBVfYQZ4Kj3Z5E3v0AhGiJrjsMjf+Zz
NDGSv7p0KNmBaq2e9gxoJIYsuPx39R+NSplA4qIOmq2Tn043NFzyVdNMQZsmR22aMWxoUhV37Wfs
WdTGoiX/YZQLN4Fw44WYTaBKDozjznbkKbAnRsIEV/OdcTXbrQK49NdqPwfYs5NGIUCdYlbpHlbo
+Du2wpIaSMjfqnCZfMoJLnQz0RMxO2gZ3e5ewP0oTHC/CvYCB/OQ+nFpJQt2WBlT6mDkVfIrIWx7
o7DHvJXyB3EB0BNEO+ScU5nkb2boXMvHMsZzFFqzLYg6GxCd9JobANlvBiMK7pbS75VWPGiJMbip
FkUjZZ3ZaB5Wsmsj6wB7ydLTK9HBC+zUb/lfGIDHm3Wagv+9YR6/CrPTbmuVJx6bpnguYbtk1O0j
a4Y3gBRlnbxcVjzt1wmNJ5l7/EeEg/ABBfODY+PV4i3p+3zGH4Nc71JLRkOHHoCsduRAdzsLVp41
hPFz0GpsqK1YQtMkNFELkoy1n6nXp67v4BCMnpeGT6xQYhyGjiN+CHPksV52htA0M4hQZdRxoABe
cpBMgs1NPI22roDiJ7WfQwIVHb/d2vC2cXLSeOVtUNIWWGuUJWzam9h01gRL2QQhYmHy+rrKEpd3
cHnQ7G0S4/ERbLwgZJGV6a1zFOA+2JjBLUW2NAnIryfW4h0i3i2dTvm3gAnxpv82mr9XZKMwe9Bs
qA9SPRej776G/qSrN2xcM/GrvcqBwQcJgx5FGD5Iyuu2f6/4M8RO63Wl2IzNEX9a31gsty5/qv7+
52EV/6229t9u3UINxKU/Em9BnQV2sRcCJBsq2+JfjJ8CJS8LqNzGBIv49x/G8Q/j+Idx/MM4/mEc
/zCOfxjHP4zjH8bx/x/j+LA6xR5myOHWsYd4oLqaf6l2NwQMY6ixPKBdbR0ZzaMGp0fEsaunRu+k
dVglwaONF9XTCXICDBZlMtKqp62TBhRCuL3Z69ntznhiGN1eGxmtbmPSOcatJjLaqDVunEzazZZ9
3G1YwJuhuUPG8E4jLS1K0N0SL1pWFs1Or1tpHxknMHMc1yyHRnYNuXa3XQGjb3Q3rFzgMYH5Tnzl
5Lhm/MvGY6MRGZWDZqPZqDXatWbvp8ryuPvYbXMTeOZzhEcgXRdun0HvCVmTe3j8SIO0eCCIG0fc
ZOZ1wCvxbjUKURhI9ZlSDqt5JRpHAKwFJBSBm8ECblz3n7E1uxte4AX/7meyJPP+N95EyCf8eeuo
AcKe3Q6vz3rwBen2WL09UW+NhnZvaPfN9J4Xhj00djAID6MGGtLGPlRFEPsBAZ2EFzLBRcJtcFcB
lxBGTCaqA6MLnowezu4fPvFe9ITHAdi/QJuFoR9Av4VOMYvGRxZ160L04R0XvZ7ygGodEa4270ZX
Um3mNLU+G6KXSNUZErfResJ6Be4rY8IORqcA4AbTWEHksg4/jh6+fLy/vVCkzeV4QNPg082aKAl5
izQX6B4j5+yPCCkCdfcXKOcI+lJCUlysfhSEYBVQ10WCeSaY9mCLaMuvnzxnCb3hauku2dflWosd
VttvaTmdP0zRCj6wNsRUUKwlp148ueijXH+iCg3/qkIzOg7m+NEwGmV10JwjtOdoxBtVR7RVvDvk
37hoigfeVMQOch2mPtCF0zTZJSIwaY5+G5UlW8aQd04ZiX5fREgRoBmCabGSBJSIenc1Hs8HD2fa
cGRoSj9/KEu+vHQwTWUkrwrzgiKdgYk+B/sgpPzKqEvMQPJ7bEPH93CfMCviU3Imvv5EroPmC7oV
27TRbfbK0kUsKV7XPS9NH2IYim59Sxf4rn8+kEeh+mCL5rk+v7lALpgJihyGsb8gGcfUBk2hFNeq
58j+QpktWg4zuYuqD1TZmkfHqmxBxBYo8X/K6qaCp2mOkQ1c7XEMhDtTGrBde62Mta5xgxqJHeUR
5n6NkC43VbUnW9r7zO40GkZZtRFzS8MNGYgdWpoGwZnn0cizkpBs3tb6oy0D8iv2CHIutJ588uap
U7C1eXfWEe0ya35BzFcsn4QgCyVM7SJCGUYJ0sQAdpHhHvuUhYoUGWlLt7tDwZlP/LLtGiaKN830
s7gsAwcvUEhl5ZKRNFk0F4WCy3MNZnpZYyhjaJopgvxqD02SAwQxP9MQn0PvyaVMKYqQqohX7pe7
sqTjvEwzKTS7KNJCE3D1uTaUlV1O082vgsrg7cMmg7BLbxtC70TOpQNSfAHTRNHf+iNFzWkmF0b2
R+88CmbD67KHko6juA6/ZJivGY7AA8auJJlK39JgIwu5Hl5zfA4rbxJKgQBtxwiOvbHtLbYYigCs
0lQZ7VUNYVG2gqEbUhLIrnc6Zb0SpUijEi3xyR2mPeWWIcDsnOLewV2fr2B+UJy7hKLbXJruEDGb
64uy1MeCs5vZphnMV0+IWxY5jl0V4xVy0bz/rZ5yADEfsOuDOlKmtJymGhyagzeiXoB+eyh7GCZs
TTODUbzRhpiB2ejYN94CrBPoAnLfXXu2ZcYWxuc1ZeQZEJXq5KVMoWPqoF4gFfLZRz568pSAY0JR
m1BTp4MFdUaAtCzpkkKhwbLSC8QAn56ejjAg4VyPwjmX59eLe0kWfrelsX5B1vyutEEXczNNKFj8
KR5RYDC9W+FaTCEhb43vsfn5Sp0CYoOYf7bfOrJkKGmIIQO2XT4chpiB+QJzoyyfTFbl6+jyPTwR
mIZsRb7m/vIk7EAUCYN6V0SwM+cJrQLRYSW5ZKo2hkRLSGINZ8QhfmUEHw4vs6RO6Au2QcLVNJFA
FHBE65bXpiDJOV+f+XTdl1ssJW3pjQ8zzIPDv5LnqCyRJJbQTgmOomZkqi74+jkwmQOTRFtMGMbP
cqQyIajttmamnKPFBDkW9U5K0+4ZR25qcQw7zF0D8FscYsty5DTNeNTCPGiJFg5alhjXkFiapo+t
GEbR0Jxu4q/b9aoE4B6zC+LRi8iaw4N7sO8f6AAFq+rvJcmzo0X/GXkkmH1uym5jSlKboqtH3HzM
xnwZtrx4W8oRnMcEQ35VNPISgKbXYi+CpArT0oeIR+Y0mFOvLGFSfnHwhSPIr4qIIqz4s6FsrWYk
fWlVD8DQGbxgVwZO5TcaBRNSlkwuMJ4C6yDJWAEsxTqaGyPCzkrgOQJxuCkXOSEZZkvnuUGn0Lfo
7lcXjjeuBe/tbbkcW55Yo0Pd2qwPDLk+ddTlJomouVyarA6yI6M0zZewA/8jK3+HaC62GZhVfQcp
xrhCfiW88QWz8DkiRrNVljQ5R24Y5SiKifSCD5kzrCtS8cH563ntAwpmyOPRcFl+/cmWUIj0Vc2/
bCcBhFby2Uw+jeTzDctPUqGm2f91LP4UCqT2aw+8OMWHlohri8A1n2FF4JLaemTNbPr04fPNxc2Z
aQ76D7u4zndoAV6ppSz3xhRd1bT+SisqAbGDHP3h4IFekMCizJalUehraTi6N7mclxjg5u6kaSZl
cyA7KBRuJGP2QKkSiFPIekAqTqNtvpBYFGfXbE4s2jvaxpn7rg3MTXMcYws5tsTKz5HuHMuXkoIU
Vkkexk2opV/chNu0y/sq2RhDGeo1kUYsO3EBb0LsBsrKU0591T14X4ElGGVILUvFvaKI4SFmiuA5
TR/GzZrVRKrw3fblZaNR+a8K2CM8x/PGmxCPhKWZ549xAaaZoZIu96gK8W6SN5rz4b0dlAe+jmSd
lpHkeuis5xm9T3AsLT2/Kp4vdnl5tpYqxmm6Kmu9kHZzjTyorxcCz/sukVye7bDUQ5mr+h8pZYsn
9Z1+p7jH/ykr/JVzNM0ERHZRqCWGI7kN4G5reHJIplcRD0i/T48CDOJPIasL7APqrtS2kIjqkOjp
TgP18Bj+L0uChJ1p4hgB8AQLTEazVaAPxJorJmRCeGWZ+g6Fz/h2WPKSocu5mqYHxUekUOQK1FR/
hkJNRQvSmqFlvKSed2oGSf+vSVG9RBbfYZHEE77iBQHfejiopfTqBs3NweZXJehtwYar7RARNsJK
7eS0LTGLOWXIpp2W4apa42T/1pVYguJOgUiXhRZHfQfjiSxRTNAVSLNITsLea4bVi8Fnwnhph1Ue
gGH4CTG7+mLSQgxwl4yFhw8P95G8IpAQ1jJD3yNfaRfRYly7iHZHx9DcWmahRJRFbBytLfx+8uYe
ffI+MlV9Hu8fP8o5wkyc4djbnJQA8vWdKKR9ByN2i6byypVKV9PQGkWWrt6ykSBduoIiqMVBOADC
NHVMu0qewDwLVk7k3vXrKj8+y9BL5ED3dMWW93yukcmv5nZc8BAn9TH7wLfSlBZ109iapoxol6wN
RvxQzQZOSdusG+qCY7AszSeOy+XpGvyz+C6RqTeaUf/r6OPZUN9ZkNFlUbpdbQliOaIIKjJ4QclK
Qd+uevvWzUSvTtiSIfRailkAuAOQM7OiAhA4M6O49HuMiKw2ROU+4zhRV6nZjPh64KCsfsHLu+Xl
8WBBel3cdTpzwFle32iTkLUlz/dN95BLTjfUZDj2S/wQqS/rWRQKWctK0pPekUMipzT/PuZmmk8c
gZ8mT2xfBn2hK95FhE0IdmxpN2Yt3SMaMozrLgLtzeqKtNmGI8d5USlk9G07rP5PqwWQMlcL4iZV
C3DzRrUQd9wRDrXUFpW+JQx+i7m/9vKC29+9NVMRpPhk+oFeR95UUZYZaUttgGcazp6eSssri9lx
qyAuP78qIsi3uygg1jldSpLkNNXyWzN4vj27Zac4ZmWbpgxjqxwfPb4a+SCOEs0EkYhaCEqTg2+v
QszoltUoGUPTzDHsbbNn3OqSQFxmhq+w7IYlBH2ubq+5YVQkUFmlzQQSS5BYoEg/iy2wLQeeNUOe
ui9coq6t4/y1IklQlJtCeRmRNV+JjEJ51Tcnqh7lmroYIgd74RujcWr0b0im01Ws+DJBpFz/uEBw
mjOMe/fchFddEhdq5BdKvBd2RSvk1/dz/bt6Be9YDE1CoeaGZImdq2jV65SWFeVzllPO0jS/AzIr
2w1ddI4480Iy8pGrphfJ1C1LrejpGZU2Twhm4FRD8QEU7/P0IhVLgTRe9Ew83kxKEm9G1PVORxWH
EL6BhBCPv1JaeFnlynN3UzzydSEfgqFgdubZ6pYomaoO1bXp8DsKqPe08rzyNq1LLMGLyKHsYKng
J2hvXzVVMtqWiN0vdOa5yGJUDDUt+Xr/NQ2FK9grKRzpcg9lo7Kt56x4285wEAo3WWrZjKYnMWsd
lx/1kuiaX4a77WkvaMhnUPjxSDmqXWvAp1O4q1Hmg1JHU1zPmXFXyUG+2g9Sip6b3iy0PveGSHsQ
F7z3vJIjqqcy/JnMa1xaZa1Ipm7ZJZyt4r1pGVKdbEXCX0KpyqeLxEWZpoRPudmjWlKmdYlNXdgg
PEc23uhWu14xulS9uRcfr2X219bXm8nD8yU459cX2Wu1l3KDDkVv6cTpaMbbnYSsWDBSznl0P4Nf
WM9fwvTOdDUfE19ZVXyIQsotD/YFOcSuHDyBfThF3pSHJn5SxO7tH/GXmSZKXwArrvMHS8TPq1Gz
7jLaK/KN0AL3qQfqjq8IDgdlTWNJ4cUl4C5OYgsqzaTSX93A9Q0jWhb+24uvpqmUvbfqAlY1nudW
V0Xh5hUDVpYIc8n2lUTV9PT7RjClgsGSUlDsF7+MD1EC48XTgswSWXeGjPcIM994i1Wnk57qFJe8
w6lOM8RcxYzg93/LHjxRdPJRaLfDDIWgT0KsbEDJiVumRzmJtvouibk5lh3WtWIDYOhEwbppI6hb
AnIbzJuiwSzJikozjApmJkkYS7SEhMiJl63MAAmhvJWcIvLGhRZvzXuxmq/mcsYUbRX6r83jFBDK
yeEUrIRVBqaSnryckbRWWkt/yQ+hrDxg5OoHNLXesNj8EGcnS1B2W8vJodUzHlxaRn1FVHG/RW+O
Zmj8/Gw0+Nx+FlKXPCNumZQWPMj4g7wczy6pIueUBuEQ2cqxRAnpFRsLptI59m7Cb+DJM0yMRuNo
00EQe0/ddPlxciEyzs8BzS5na3nzD1SdH3KaPj1oelTIg4Lrq181S7gUFznnzg/USiBJl4WsSurz
M2YUgzIlqeplLcI8Qo5LvYs3WsTJsOUlSr5gyhtMzARNflX8AJlgOFg7OYbTthy06EQWah77uDS7
MSt5B2ufEVs93yulbN+HzRsfiH0oFS9f8Fje6GomJRTd3dtnNAjG9EnxLBOSLsvJxon3DZGVtLQ9
1+EvKLjwv5F6BpqvzqyGDg2VA3sFQdvsu3Ze7xeCn6vcGV2iJF1vU4C0/cb1jHjCoR7m+deDIICe
Q9LOL2ULityBUbhyxLDie6gT/4ungk2I40hjMpaRn9ibyLql4QcuPyXa5ht2Zadbom7pygNHHBuH
nCzaeIVc/ciEbVGFgrp0U1mmKQHeYaHD4Rt7k4lTPiZCIhcYyPjpenD/8fz+5sPgsBK7OIeVj7PZ
7MxZP/tp15zR3Ji5pHynVJyPnIDLayYtzjRl9EVHPz9IlFgOVo8xlqlbquGK8L34h5WNCSm7SS3Z
59niXowlLmgHsxymWR5PXDvHS3uwRb7nb8P7j1dnd4P7b8/tZqvyPxUzajRQDwPSCgmCCAeV+Li+
yniVPGt+JgAE4FauSHid6CmN0e5J8kkqe74nRN6YlFOLjSe1EnYwt/iK6MgjalRepupWSeu1c5jA
FxbBpHBROfjv9JKfkt+fMRLUhoy4GJ7wzyi4/fzTG8PciWrceICTJMdOGdiC7TllNmbB2qyT0t9p
KW6zS7surrI2p6DbYUuueI3/f01dvC5u/uS9BM7FKrQGqcHaoa/nP50ldXX597RUayLeqat19+zr
az5v7w2LUS/+CI0CbTcjSoUp3SbHIGiH56WULWk7fYz9OV7sGaV60zaKBOFOo5gvewmDSz+nIya+
3NxGkY3Z/OeZV1EYRHO+BWuOHELm6kxpNEvary0O7xDprcnJHSn4t+zVlhhBRd14ixGWk9YSwt4n
8K0Jn/zkyD5n8MVYirc7/6mP/BdWVq7DqVCaOOr7yGd8F0NIuJ7jZB8xEDnEqf+DlyH2ArEVDaoD
PDos/+SIjULl3iHjpSggowB3LwgUkm+pTII/HMDaUn7KJP4hlex+bLkonMkUi2cx2YgpNLbyQyp0
cXwMnZX8dmL+jYgpUGzq8rhJo9EyjCb3/b4HSeP2ROOCAyJCE/kbk1D5zZWprdy5ysMZChTMQYg4
ZOWV0fBWqUC+r8QeJxuZuAzuOP71HPlb7grqTPzYS3JV6fB1mWYNRkilVmk2jE6j3ejB5T9v7NNK
z7Lgv5Mu7vY6k67da+KONWlMmt3epH2MjW7PaqLxGEy/f4rW8UKljoYXH5XWs+mjKFUnxs2ovDlT
2yfvho/iR7LETxZJU6dPA7JUXghnDCM+HIQxZPBf6zmsMgzNyLvkNIorM33/Hk+ceJVUqfWZS5Vm
iZeYvt4pFR8IbIHSOYIksZF3DDIdEw/xEzpF0i2PfYY8Zkie1f6hdX+45RKsfUf8rqJCXCHxJo/h
8UnmmfjxlNMRt6LGSf79P//8XxL2eS8=
===END CRASH DUMP===

**Comment by hmy2001** [comment]
Fixed it. Please redownload latest version.
