### ISSUE TITLE
Download Link? Newest Version?

### ISSUE THREAD

**Issue by strich3** [BigBrotherTeam/BigBrother#166]
Hi can you send me the newest Download Link? I am from Germany xD

**Comment by hmy2001** [comment]
Sorry, I forgot commit to master branch.

**Comment by strich3** [comment]
Can you send the Link? xD Thanks

**Comment by strich3** [comment]
All is Ok 🥇 You are the best 😊

**Comment by hmy2001** [comment]
Please wait about 20 minutes.

**Comment by strich3** [comment]
Ok :)

**Comment by hmy2001** [comment]
You can download from sent link after built this.

**Comment by strich3** [comment]
Besides, what about 1.13 and 1.14.4? It's just a question!

Translated by the google Translator!

**Comment by hmy2001** [comment]
non-active project.....
It is difficult for us to develop it.

**Comment by strich3** [comment]
Ok
