### ISSUE TITLE
SpawnPlayer(npc) is buggy.

### ISSUE THREAD

**Issue by Driesboy** [BigBrotherTeam/BigBrother#17]

**Comment by SuperMaXAleX** [comment]
Cause : packets aren't the same.

**Comment by Driesboy** [comment]
and some times the npc dont show

**Comment by Driesboy** [comment]
![2017-03-24_14 06 15](https://cloud.githubusercontent.com/assets/15795262/24295482/2cc51f1e-109b-11e7-9121-33e3521c2cf4.png)
if you teleport back to a world with a npc i will

**Comment by Driesboy** [comment]
not all but yeah

**Comment by hmy2001** [comment]
fixed SpawnEntityPacket

**Comment by hmy2001** [comment]
Is there still a problem now?

**Comment by Driesboy** [comment]
Testing it soon

Op 1-jul.-2017 10:51 schreef "hmy2001" <notifications@github.com>:

**Comment by hmy2001** [comment]
Please use SpawnEntityPacket to spawn npc.
