### ISSUE TITLE
A Question (Please answer)

### ISSUE THREAD

**Issue by Altamash347** [BigBrotherTeam/BigBrother#170]
Which branch should I use which one is the best one?

Does the default branch has 1.13 and 1.14 support?

Just tell me the best branch with least bugs.

**Comment by hmy2001** [comment]
base: Share changes.
master: for 1.12.2.
1.13.2: for 1.13.2(EXPERIMENTAL).
1.14.4: for 1.14.4(EXPERIMENTAL).
