### ISSUE TITLE
Composer...

### ISSUE THREAD

**Issue by Call56** [BigBrotherTeam/BigBrother#173]
### Issue description
「Composerの依存関係を初期化してください」と表示されます。
### Prerequisite
?
### How to reproduce
1-プラグインを導入する。
2-起動する。
### Server log(crash dump)
送れないかありません。

**Comment by eternalharvest** [comment]
@Call56 
おそらくこの問題は #136 と同様かと思われます。
プラグインはどのように導入しましたか？

ソースコードから導入した場合には、composer をインストールして `composer install` コマンドを BigBrother のプラグインディレクトリ上で実行する必要があります。BigBrother は、サードパーティの暗号化ライブラリ phpseclib を使用しているためです。面倒なことを避けたいのであれば README にもリンクが貼ってありますが Bintray から、バージョンごとにそれぞれ最新のビルド済み phar をダウンロードできるようになっています。

できれば Prerequisite のセクションには、使用している OS や PocketMine-MP のバージョン、BigBrother のバージョンを記載してください。エラーメッセージが表示されない場合であっても、PocketMine-MP の起動から、BigBrother プラグインのロード完了までのログを貼ってもらえれば、読み込み時に環境情報をログに吐き出すようにしているので我々開発者には問題が分かりやすいです。

**Comment by Call56** [comment]
pharファイルを使えばできました。
関係はないのですがプラグインを使用してJavaから参加しようとすると
ほかのプラグインのエラーがでます。
これはやはりそのエラーの出たプラグインの改造が必要なのでしょうか?
(普通に入ればエラーは出ない)

**Comment by hmy2001** [comment]
そのプラグインの名前と配布先を教えてください。検証します。

**Comment by Call56** [comment]
プラグイン名: SimpleAuth
配布先: https://poggit.pmmp.io/p/SimpleAuth
注意点: 私の環境では別のプラグインもあり、SimpleAuthHelperと言う推奨プラグインも導入している状態です。

**Comment by hmy2001** [comment]
そもそもそのプラグインは対応バージョンが低すぎてロードされませんが、改造を行っていますか？

**Comment by hmy2001** [comment]
Githubの方に最新バージョンがあったので解決しました。失礼しました。

 結論としては、SimpleAuthが用いるクライアントデータをBigBrotherが実装(代入)せずにSimpleAuth(pmmp)にデータを渡していたのが原因です。#abf5e9b68212079dd16abb24086fd2b08e987a4e にて修正しましたので正常に利用することができます。

**Comment by Call56** [comment]
すいません。
composer installを実行しても結局同じくエラーが出ます。

**Comment by Call56** [comment]
完全に要望なのですが先ほどの修正版をComposerがいらないpharとしてくれないでしょうか?
