### ISSUE TITLE
The server crashes when clicking on inventory boxes as Java player

### ISSUE THREAD

**Issue by Benjamaxo** [BigBrotherTeam/BigBrother#174]
### Issue description

When the Java player left clicks on any inventory slot, regardless of whether an item is in it or not, the server will crash

### Prerequisite

DevTools

I tried this on both PocketMine 3.17.0 (by changing protocol to 422 and running with DevTools) and PocketMine 3.16.0 with the normal Java 1.12 download, with the same crash occurring both times. The crash dump below is from 3.17.0

### How to reproduce

Open up inventory
Click any square

Unlisted Video Demonstrating Crash:
https://youtu.be/V_qNJLiCjHw

### Server log(crash dump)
PocketMine-MP Crash Dump Wed Dec 16 15:45:07 GMT 2020

Error: Undefined property: pocketmine\network\mcpe\protocol\InventoryTransactionPacket::$isCraftingPart
File: src/pocketmine/network/mcpe/protocol/DataPacket
Line: 205
Type: Error

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: BigBrother v1.6.0-beta

Code:
[196] 	}
[197] 
[198] 	/**
[199] 	 * @param string $name
[200] 	 * @param mixed  $value
[201] 	 *
[202] 	 * @return void
[203] 	 */
[204] 	public function __set($name, $value){
[205] 		throw new \Error("Undefined property: " . get_class($this) . "::\$" . $name);
[206] 	}
[207] }

Backtrace:
#0 plugins/BigBrother-master/src/shoghicp/BigBrother/utils/InventoryUtils(852): pocketmine\network\mcpe\protocol\DataPacket->__set(string[14] isCraftingPart, boolean )
#1 plugins/BigBrother-master/src/shoghicp/BigBrother/network/Translator(264): shoghicp\BigBrother\utils\InventoryUtils->onWindowClick(object shoghicp\BigBrother\network\protocol\Play\Client\ClickWindowPacket)
#2 plugins/BigBrother-master/src/shoghicp/BigBrother/network/ProtocolInterface(256): shoghicp\BigBrother\network\Translator->interfaceToServer(object shoghicp\BigBrother\DesktopPlayer, object shoghicp\BigBrother\network\protocol\Play\Client\ClickWindowPacket)
#3 plugins/BigBrother-master/src/shoghicp/BigBrother/network/ProtocolInterface(379): shoghicp\BigBrother\network\ProtocolInterface->receivePacket(object shoghicp\BigBrother\DesktopPlayer, object shoghicp\BigBrother\network\protocol\Play\Client\ClickWindowPacket)
#4 plugins/BigBrother-master/src/shoghicp/BigBrother/network/ProtocolInterface(409): shoghicp\BigBrother\network\ProtocolInterface->handlePacket(object shoghicp\BigBrother\DesktopPlayer, string[10] ..........)
#5 src/pocketmine/network/Network(109): shoghicp\BigBrother\network\ProtocolInterface->process()
#6 src/pocketmine/Server(2387): pocketmine\network\Network->processInterfaces()
#7 src/pocketmine/Server(2154): pocketmine\Server->tick()
#8 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()
#9 src/pocketmine/Server(1588): pocketmine\Server->start()
#10 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[46] C:\Users\user\Documents\PocketMine-MP-3.17.0\, string[54] C:\Users\user\Documents\PocketMine-MP-3.17.0\plugins\)
#11 src/pocketmine/PocketMine(304): pocketmine\server()
#12 (11): require(string[101] phar://C:/Users/user/Documents/PocketMine-MP-3.17.0/PocketMine-MP.phar/src/pock)

PocketMine-MP version: 3.17.0 [Protocol 422]
Git commit: 3903b70ef5747ca8365ccda91d3e4ff0ba45816d
uname -a: Windows NT DESKTOP-VEU7HVV 10.0 build 19042 (Windows 10) AMD64
PHP Version: 7.3.23
Zend version: 3.3.23
OS : WINNT, win
Composer libraries: 
- bigbrotherteam/bigbrother 1.0.0+no-version-set@unknown
- phpseclib/phpseclib 2.0.17@3ca5b88d582c69178c8d01fd9d02b94e15042bb8

Loaded plugins:
DevTools 1.13.0 by PocketMine Team for API(s) 3.0.0
BigBrother 1.6.0-beta by BigBrotherTeam for API(s) 3.7.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWgtv28aW/isDJUDtriiJeli2CgdNbefGuEmsGyvNYqvAGJEjiTVf5ZCW1SL/fb9zZviQbOfu
TbvYu0CCABbncea8z3eG/KO1TLJI5jd3KtNBErcmg3YrDyLVmrhHvWN3MBj1xu1WKHV+kWVJ1pr8
0cq3KaZb5rndipTWckUjH2JfLYNY+SLNklRl+XYi0sS7VXmE0fk8VvkmyW7n88hL8YhFeeIl4Xx+
Gd+pOE+y7SyTsZZeDk6mkjZOJs8DfZbJZR7Eq6nMchy4LMLwVRDSielaZpNu92zS/aAhQHeh4l9l
9zzxiggEdXfKp7/F6c7bqTPouONOb3ewQyS6OvO6Naddy2iX+OyWbHbPZS4NV9iUEiOGiX9xMzaG
WNea9Hsj6DqTHn7/0nrWE2lYrIJYd38KVj9h31plTgTFK8OfXierdeCljelukQeh7lbq+0CPB8ej
/uH/UPE1V86Lmxut8gOdZ9D0L+7wk9hVfFsskiRUMhaHkOCZ+xXclpphK4cSHB/0j4bgtVw8n9er
53MWruEcLJ3zIok/BrGfbM7CwLs9SBa/Ki9/gkIldy3xNJTb+Rx7QZP/ereGnFEDy9b/E7JN7UmX
MVYvYduD/ujoSRErBmuVOC+CcussuVYZAvPLQp4rfZsnKQmmsrb431DI4C9VyGB88s8V8mCb8yJT
ngrulOHr/1wnw79UJ8Pe1+lkLWM//BqVlHHe+yQ61T8WbCSeSGjvzN8D9yt5hX491IoDPuVo/xTr
6v3B8fip7GUZqChVtC3N8VM03dFwj6aZcV7klEN48/ETm92Tky9tnhpWkMqYyslTVEbHx09Q0Tmy
q9nt9va317XqoD8ePEHh5sZLYhi08Cof+ElqdYaqrd8k0m+EQHO7za9vZRC/SVarhlcMjz6Js8l8
zkV1PueqCg8qyyqs+0hdnc+r/aPhV+23ATWfG2W4X1DGoLdvFG0Ubbb2xYHrYkGmfiuCTFVVred+
En81Zjhsffrcbql/G3T0p0EJpDGWuAniuyS8U6QXkEQGhC49WmvmMVbHPka9xFekAvfkCFPz/DPG
3JMxfvOPYx7sfv89P53wk/he/JjKTEbWdcTzWAJ8tlv9Xm9vQRTcQ3fi+Z0MC7PCtSv4oV8tz1Re
ZLG4SwKfZwZ2pstPQ35KiwWyulgWMatTGPDDh7ftEYd/8PoRr5/n+TpLNiJWGzGfs3EP5o+adN4S
HbFS+Y1H4XfwPF8H+hBD89YEEfGcp/mcwx+Yfq2qfo9U9bn1+Rsq/IYKv6HCb6jwGyr8hgq/ocL/
t6iw3VqpWGUyJEzEsGbS2tkBphawSH331jJ0abwIQr81cY/7g3Yr0De+umtNljLUCuDLBlFrMuz3
cUhA4Gxw0hssxj21HI2HY08eD45GnufLE9cfqOFy2VvI4ejYPSJEVFheTPLS4t1MnF9c/312NXV+
vvgwfv3zz8LtdXqCeRDuSW8IxZWL3d6hePn2/GhIKHCdgsy4M+j0B3j8XcU+y2CfMX2TaDro8t27
GQb4YQPcSFAxShMo+iYMFpnMAqVJSYtgtTA5I1cy6taP2Od2wNN/xIljteUAl/xYxLdxsonNYVp5
oNatfmFTH5vc8Y8DT44Wx8f+6LjvHZ2442Pv2O+5S//E7/UXJ0PljiDjYnHc+lxhX+bnXN3NAG90
w4DVULtVm83tuAM2myzydZJpQm61pcUMwpA7yDSgmQFJQs8qlotQQWcIUtjVVyk0SJsxp5Nlft4c
iCQD7vJ8St0VJyHCGXPXs5fvZx/IrTZqoYOc+F3nearh2PCSdbHoQO8Nr+1WNCB3A8rX4u7g+6bA
R52es1C53BW6Xv5A5vHXy/x4Udlh7V/TwC6bjUfjANRuKBSRPTuWMU5imLzSsbCf3bf1bFo9ibMk
XgYrQc3YPJvHz2aFEufKE+5IuEcI68nQFX97OxPoW3q0IJTxqkCfeKriFT1HSe6fXuYfpX4lpaQR
c6JDdnl0Ik2y/NQ9cQd9GlxhWYR27JSpR/LeSbnE61O3x0M6lZvYoVSiuAM6dVwa3qyhNCcMdH6a
LJc0Ygzm/FaobLs3lqHAlEMyjhM0U8qe40hvHSjTOurTJKYlyyTDfMWZ3QiF+l6SVc/pXWrX+8Fy
GXhFmG9PjUycTQkMI/SpAdGnrDocExq9AAeEfj2mlfIbS6gzPz2/ePXyw5sZjRL7nRTVENv80+/5
HwQp8sTR8k5ZLu4CtXF8KERCutNjGrpfJPcOeb1dQumnqjmdbRSSMwiqoMJjPyjANnWZ5A4CahA7
TgX3ELO10kqUcgmZKQF/FEkMX8rXMhceKTgXCyWC2AsLHz0nyD9wQ6J1nUTYuSQC+zS1XKK/ZVfX
RFIsMiVvxTYpMktLBEsB8wTLgE+AZajlD7dE+B2a35JcF52vhG202CTxd7mQaapkJkh7EYT1ZBhu
iUNqf43cm7WKRZGuMumDQGcek+saYpN5LMSzj2tFjIk8wSmxL0DCQgfowHZCYIqnmdUwwTEQFb9U
zvpCmQw8JQz+pZGIKBvHK0NsIriO0oReFzmqWuzYWxrq3g18Eq+lFteYFueYn7eYwZdhmGwEBQfd
VNg6Ie4CKf5B0UFrOEwcOzURlOR46wVHjN0jwJ4gn6drA+iGqC22wmqU1tsAq6YbPD/7GEAvSQz1
St8HltHGCqRdgp4iUlIXGUcemnV4DDENHQH0yJC0t0K7FAu+4xAH9lAkokOibk5EaCvKJw60TxBw
gmk++10RLaAcONdLvY29mdS3gsA33KnDCwCefPbwUlJats4SJAcYEct1W3CUChvNCIu2IDQAQai4
sG6QvGksKmI4Ei0xxK/ZypAJzpYl9wEcTUENEIkdOK6YI91ahi6X5LK0hlyzLYL8O6gvz3ibryj7
sefsbRYHkKFA+PRZLSyGYyWdMKl9l5XsHFkRx2ROnzJOkrIRGEfpDvL/nf0tomC1RkxnUq/bzRi0
jkMaybIizc2oURgpJgJvVi42LmITakKwmLiQdOcFth/ngHyEfC6BouFdnYajYbFjFlWehqqBPJ1t
TWz+LUwW8B6q0MKMIw6iIKcQj9RKLrY5NC6ujap7rNxAE23ePiOrbQLWPHsUYnfjGEKlk2mWcAlg
jh9C0fUOkVlmSpVHGieHtQqKVrFKYKiEopW8gg5aMZsOszYRPZICp3MmztdQs/9vLwFBni/xT+Xy
z/Gv0e8zCzaLVixZclogfVBZVH7FEJ1acuX2+kPLGCeBjxwVlj/93V/AIccFs0QZQ3gFalCMGiTU
vfIKTr6JYdlEJNWsarW691D2dS2RSVxXs4uJmL2+vBZvLt9ezsTL6fTN5cW1mF68Fx+v3v/94n1b
YJGYXWHVhfj4+urNhZi+vzq7uL7u7KeAHX30R0dWHVOVBQnXZUrEmgT01opTMmujSrboYRG4sc+5
hZc4SIXKpFkmBfwIOZGg4U0k71POZpwMqI3qYEzL7GFM2RBB6q0TualIfMYV1RAq97yh83A1+YLF
6zBbqjxCBUazxK6xq9lbyQD3UqmuRR30rKz68HGWrOQDK/lKZgtEhoP+NjTIlBPQ49rlUCN27C5h
dyF3RzIuGIM0OQE+K+CDh+2yJuw7YemGprwul6Bl5I3qEOyIK5PzjcPTlVcR+hUvAYrIJhY1/9oQ
Tpl9CHrU61lZcdorThYPiiS7jqFQybbMkqgstma3XeE0XbNpYZLGWvKBb4hHXGrHO65L3Egmy3AS
uaF1ZL+IUgOyDJITdsKhidJe57TIbmDemc1SAjyhzCPY5SMKRtFG4cMJd3AyrQtFiSFfw2qrEnRS
0qLTaq7apSENRrDYsmO4oaVP6onaI29dxLe65P1MpjQaREWEGovymomyBSBDCtPkGC5qvVK8WFVy
xDz0MWDu1HLEBzoEhgsU3WFlsfPETO37NGEjynqGvllchpChZRc2JWPk4HhoxlQl2zlYYawC+Eja
A3cGYBgqKd8aC7PHSFhLh21Wn0ae8mRaXKNdUmBI3YCl+2VSX/LDeWyveSe2RACarZPQQMyFzNFk
EhJnloGa4EK2yHBuMw2QnTWlZaEqsGnK27OmlcopSqvZNifibeG4DQOy8fhgJy+ZsSWAs3aNY7nn
JAjpG8mppWGgT5vpjaFhqyNeAwvCl04Z3Imz6Yc29oKHBeJrE/hwe8YKJntW9B2mPxFHJeyuEblm
7TTWdsRLH4lqLcNlFx2laRN8BR+2R+FQQTco5GCNQKzLXoNYsxW5uKesRhBThm2TNOloe1fYEbOM
60XCSPrDNJ6WOLxuEanNoE0bVFSiWaRx6tjnvcbnrQ1IHfyuKlMTYi8trKkWWjQFRG88p1F1hyd9
s+mwI6Z2TyizFW+Qtle1bsInLjO5IulgLoil05DBDDWgEZinPCAzMqF5J2Q6arpcVjoXb2cfmFMN
kUjsBXpJ6uDZyvVxpu/olGkoyguHdk2YWwoAXy2K1aTsZV4Il3oYi+TWiGKeF7aB1ablJiePdWJq
mnUUl4iZvGWona2TRHNbXrYwqmxSObn5MpdCy7syidKdSHm7Q3N1vEvUdGQCJfMyx4BTc1ldQmZu
t+BCDFd0CoTG8CVOvDBIBe+FHt/KLXRIzhIld2UHS+nf5kzOW045Z47UdbYob32alwozvhUwDmA+
dTX3KbzWWrvQ9nbCg9fnJi/YPY7ZMxEpAMVdENIxJufZeLanUNKW8aoC1TFtC/drR7tctXOp9OhF
junyXkZJQT69NMnZujip0tzmcTGicObeHYah31xNsPk915bGZhY8VqZXXChDbKGW5JF8H8jlYF16
ABudrwl3qpQRnw6qxEdkCrnPqn0dh9MUCsBjXPYeZ1NmoAT/KB0RzJab6W/FzYC9mzppp0jhkUo3
soVHBYgP4tvMxlXM5TkftggTQpEUkqRPlZGlgWuRuiJhpRP25qGsdrxnR3TQc0RfPBMr9Cy6Vk99
u1FpqPNQRTZYNzLgpgaJA4jf2CZN0iIsndE+UNrnNTZFDDhBMBp2UhvWlF0pUlEZLM7kC01znzOx
FY+un7jHMsOmYFh7gZH6YsCv9Ub+7tAXPntDVbjtDqdrQLNl0rAIoswxd/HVynVClmFWOmkUpZ0g
YY7jJN5G1CMgQHK6bvN0zTo1PnZe1PMsAqcsuVpl6DbNzZK9hjLdNn1Vc7svH/OHCL46v6I3g45N
gqYWUFLYKANEJX/8QydqZrwWgMc6jStglJ5K88Y1jXEeKBUGNfPWmVD1Ysfm7iae4vGkqTpA1Jj8
pHHN00Z+TNeyLei9DBesvIIsSL1LhTYaJkQGiqkgmNmysJhLI7lzbWTf9zQKTgF4htrGWaxMFpYg
W97Ml2c8sLSRtWnqHD10lattRSKitL4EDmRZSph0IN+H2U3l3WenPsDONE8otfnlmmfTtrGuiYrG
NYOlAfK51Wd5obC2g5wxqCOwINNmDLqfBY73GWUFy4oQoDoEMXfylIHKLtvkONCzKbKsbDIMpLYQ
HqhLRmlYPhEIAI/WVpPSaGYOfkvXPRPxC1dv1M823/98IqKMzusy2XxXwGIQksoC33bY5csXbp0f
q1hc0LlCawaT3JnBPgF4teW2yb45l3kwPwW9rqGqYKpXfeJEvHrzcjbp/zBuj07u3fbgftDu/+D+
4CsvMTn2IM8UHpBcT497JhWbp+Ho0MAecx/fbGxNhFNtgY7tvRNDD744gtW8rTBfTxRZmZRLNJ9V
N/mccUAHpcrjFya6VJhTvgWALxh89+wVpxo+itfvECkYKdgPLxsjDoOtTn1FlqTcC6p7JD5tGyHv
lvCyZtAPjSwCINWt6Zl5HckLVgDTTRkxMWOkZPoAI1mVq1vtlrrPVUx+xO++z4AQmm/6Fx4w0bo5
Qi9iYl9mO2NJdOMnOZLhzqj9QLYeKLKw+Uwpovm8DMJc7RBeRTvfHaxRPprPAaLsrjnwq7Yvrc23
FdHCvFVqLiEkBvb95ljq7Ur9Xi1tI76zk9O+3h0CQImaI9fTN83HaKt/C/ljCftLjOhDhT7dwwvg
iR59kNAb4+fzS4TE2PPw/+RIHY1HyyN/3Fcjb9lb9o/Gy+Gxco/GXl8uFv2BeA7aeXKrYsCDHY1t
Jb+U7Hdc1sDvQWq+Whh16DuO383HEtVqPN5HuzZJSJx+rzdw3f4JBqbnVzuq8pMbFmV/EEPBrjmR
LmKtdxZeB5QQ/vPtjo72OMAjtaS7YmFwkwV73pHaizn+FAUS06czYHi965x1tb5hMMafPWFBz6oo
WC2CWGZb81EOq4lJuiBJCuCE5i94Bw4hP862aZ7wwIAHVv4Dmwc7bsK6GTSHMoVooLBbFcYZS3b+
izDb1ZSvUuoNnz//N1Lpa8A=
===END CRASH DUMP===

**Comment by Benjamaxo** [comment]
I should have added that this glitch only seems to happen on survival mode*

**Comment by hmy2001** [comment]
Fixed lastest commit.
