### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by strich3** [BigBrotherTeam/BigBrother#175]
How to fix This?

20:34:05 Server|CRITICAL > [BigBrother] Couldn't find a protocol translator for #422, disabling plugin

**Comment by Benjamaxo** [comment]
You must download the source code from github, then place the folder into your plugins folder.

Then, go in the BigBrother folder, navigate to src/shoghicp\BigBrother and open BigBrother.php

On line 89, it says
if(Info::CURRENT_PROTOCOL === 419)

Change this to
if(Info::CURRENT_PROTOCOL === 422)

**Comment by strich3** [comment]
Not working

**Comment by strich3** [comment]
Same error please help

**Comment by strich3** [comment]
Ok it works now thanks!
