### ISSUE TITLE
New PMMP API versions?

### ISSUE THREAD

**Issue by Xd-pro** [BigBrotherTeam/BigBrother#177]
What are the compatible forks/versions of Pocketmine? Can't seem to find a way to get this working on a 1.16.200 Bedrock server.

**Comment by Xd-pro** [comment]
Update: https://github.com/BigBrotherTeam/BigBrother/pull/176
Approve this pull request, I'm not sure how to compile pocketmine plugins, so I can't just do it myself. The pull creator has issues disabled so I can't contact them :(

**Comment by hmy2001** [comment]
Updated.
