### ISSUE TITLE
Most times, glasses don't display on the world.

### ISSUE THREAD

**Issue by Driesboy** [BigBrotherTeam/BigBrother#18]

**Comment by SuperMaXAleX** [comment]
It's coming from your world, it's sure

**Comment by Driesboy** [comment]
its workign on my ipad and on windows 10 beta

**Comment by Driesboy** [comment]
its only in the Lobby world and they are converted like all other maps its only a bug on the Lobby world

**Comment by hmy2001** [comment]
fixed it?

**Comment by Driesboy** [comment]
will test it out plz wait a minute

**Comment by Driesboy** [comment]
![2017-03-24_14 02 04](https://cloud.githubusercontent.com/assets/15795262/24295460/1958eee2-109b-11e7-8176-a2d935eb9929.png)
2 of the 8 apears

**Comment by hmy2001** [comment]
Is the block air in the PC version?

**Comment by hmy2001** [comment]
PC Air
PE glass?

**Comment by Driesboy** [comment]
yes

**Comment by Driesboy** [comment]
but if you right click on it it apears

**Comment by hmy2001** [comment]
Solution: Check blockdata
