### ISSUE TITLE
CRASH | yeet²

### ISSUE THREAD

**Issue by strich3** [BigBrotherTeam/BigBrother#187]
Altay Crash Dump Mon Jan 18 16:11:10 UTC 2021

Error: Argument 1 passed to shoghicp\BigBrother\network\Packet::putSlot() must be an instance of pocketmine\item\Item, instance of pocketmine\network\mcpe\protocol\types\inventory\ItemStackWrapper given, called in /home/EventServer/plugins/BigBrother-master/src/shoghicp/BigBrother/network/protocol/Play/Server/WindowItemsPacket.php on line 50
File: plugins/BigBrother-master/src/shoghicp/BigBrother/network/Packet
Line: 106
Type: TypeError

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BigBrother v1.6.0-beta

Code:
[97] 			$itemNBT = ConvertUtils::convertNBTDataFromPCtoPE($nbt);
[98] 			$item = new ComputerItem($itemId, $damage, $count, $itemNBT);
[99] 
[100] 			ConvertUtils::convertItemData(false, $item);
[101] 
[102] 			return $item;
[103] 		}
[104] 	}
[105] 
[106] 	protected function putSlot(Item $item) : void{
[107] 		ConvertUtils::convertItemData(true, $item);
[108] 
[109] 		if($item->getID() === 0){
[110] 			$this->putShort(-1);
[111] 		}else{
[112] 			$this->putShort($item->getID());
[113] 			$this->putByte($item->getCount());
[114] 			$this->putShort($item->getDamage());
[115] 
[116] 			if($item->hasCompoundTag()){

Backtrace:
#0 plugins/BigBrother-master/src/shoghicp/BigBrother/network/protocol/Play/Server/WindowItemsPacket(50): shoghicp\BigBrother\network\Packet->putSlot(object pocketmine\network\mcpe\protocol\types\inventory\ItemStackWrapper)
#1 plugins/BigBrother-master/src/shoghicp/BigBrother/network/Packet(239): shoghicp\BigBrother\network\protocol\Play\Server\WindowItemsPacket->encode()
#2 plugins/BigBrother-master/src/shoghicp/BigBrother/network/ProtocolInterface(183): shoghicp\BigBrother\network\Packet->write()
#3 plugins/BigBrother-master/src/shoghicp/BigBrother/network/ProtocolInterface(241): shoghicp\BigBrother\network\ProtocolInterface->sendPacket(integer 3, object shoghicp\BigBrother\network\protocol\Play\Server\WindowItemsPacket)
#4 src/pocketmine/Player(3561): shoghicp\BigBrother\network\ProtocolInterface->putPacket(object shoghicp\BigBrother\DesktopPlayer, object shoghicp\BigBrother\network\protocol\Play\Server\WindowItemsPacket, boolean , boolean )
#5 src/pocketmine/Player(3578): pocketmine\Player->sendDataPacket(object pocketmine\network\mcpe\protocol\InventoryContentPacket, boolean , boolean )
#6 src/pocketmine/inventory/BaseInventory(446): pocketmine\Player->dataPacket(object pocketmine\network\mcpe\protocol\InventoryContentPacket)
#7 plugins/BigBrother-master/src/shoghicp/BigBrother/utils/InventoryUtils(885): pocketmine\inventory\BaseInventory->sendContents(array[1])
#8 plugins/BigBrother-master/src/shoghicp/BigBrother/network/Translator(264): shoghicp\BigBrother\utils\InventoryUtils->onWindowClick(object shoghicp\BigBrother\network\protocol\Play\Client\ClickWindowPacket)
#9 plugins/BigBrother-master/src/shoghicp/BigBrother/network/ProtocolInterface(256): shoghicp\BigBrother\network\Translator->interfaceToServer(object shoghicp\BigBrother\DesktopPlayer, object shoghicp\BigBrother\network\protocol\Play\Client\ClickWindowPacket)
#10 plugins/BigBrother-master/src/shoghicp/BigBrother/network/ProtocolInterface(379): shoghicp\BigBrother\network\ProtocolInterface->receivePacket(object shoghicp\BigBrother\DesktopPlayer, object shoghicp\BigBrother\network\protocol\Play\Client\ClickWindowPacket)
#11 plugins/BigBrother-master/src/shoghicp/BigBrother/network/ProtocolInterface(409): shoghicp\BigBrother\network\ProtocolInterface->handlePacket(object shoghicp\BigBrother\DesktopPlayer, string[10] ..........)
#12 src/pocketmine/network/Network(109): shoghicp\BigBrother\network\ProtocolInterface->process()
#13 src/pocketmine/Server(2485): pocketmine\network\Network->processInterfaces()
#14 src/pocketmine/Server(2264): pocketmine\Server->tick()
#15 src/pocketmine/Server(2107): pocketmine\Server->tickProcessor()
#16 src/pocketmine/Server(1691): pocketmine\Server->start()
#17 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[18] /home/EventServer/, string[26] /home/EventServer/plugins/)
#18 src/pocketmine/PocketMine(304): pocketmine\server()
#19 (11): require(string[65] phar:///home/EventServer/altay.phar/src/pocketmine/PocketMine.php)

Altay version: 3.17.1+dev [Protocol 422]
Git commit: 73e0c77ccdc50e1531f0da734bef08de6774e1c2
uname -a: Linux eager-driscoll.194-34-246-157.plesk.page 4.9.0-14-amd64 #1 SMP Debian 4.9.246-2 (2020-12-17) x86_64
PHP Version: 7.3.23
Zend version: 3.3.23
OS : Linux, linux
Composer libraries: 
- adhocore/json-comment 0.1.0@8448076039389f558f39ad0553aab87db3f81614
- daverandom/callback-validator unknown@unknown
- pocketmine/binaryutils 0.1.12@566fa87829e007eda0bd96e39fe20b9b0d638132
- pocketmine/callback-validator 1.0.2@8321aa3ccfe63639b0d08f0cbf270755cfc99fe2
- pocketmine/classloader 0.1.1@7c0363491d1ce8f914fe96d41a4338c982adedff
- pocketmine/log 0.2.0@e59bedb5d4bbeb9a26647cb7c367cb2fa72addfa
- pocketmine/log-pthreads 0.1.1@9bbcef398b01487ab47c234a6a7054722abbe067
- pocketmine/math 0.2.5@8c46cfa95351fb0b2b30739a381310941934b55f
- pocketmine/nbt 0.2.15@f8a81d37d24eb79fb77d985a52549d68955bc6a1
- pocketmine/pocketmine-mp dev-1.13_altay@73e0c77ccdc50e1531f0da734bef08de6774e1c2
- pocketmine/raklib 0.12.9@5f2a02009f486ca4d90892814570fa13ebdc078d
- pocketmine/snooze 0.1.3@849510fa62e57512b8467e3694e9b3add97038fd
- pocketmine/spl 0.4.1@ff0579a0be41bbe65d3637607715c0f87728a838

Loaded plugins:
TransferAPI 1.0 by Yesdog, Xernium, TobiasDev for API(s) 3.0.0
BigBrother 1.6.0-beta by BigBrotherTeam for API(s) 3.7.0
FormAPI 1.3.0 by jojoe77777 for API(s) 3.2.0
BlockSniper 3.2.3 by BlockHorizons, Sandertv (@Sandertv), Chris-Prime (@PrimusLV) for API(s) 3.2.0
BuilderTools 1.2.0-beta2 by CzechPMDevs, VixikCZ for API(s) 3.0.0
DevTools 1.14.2 by PocketMine Team for API(s) 3.13.0
BossAnnouncement 2.1.0 by XenialDan, thebigsmileXD, HexiterYT for API(s) 3.0.0, 4.0.0
weather 1.5.0 by Apartkktrain for API(s) 3.14.0
PurePerms 1.4.3 by 64FF00 & ProjectInfinity for API(s) 3.0.0
BlazinJoin 1.1.6 by iiFlamiinBlaze for API(s) 3.0.0
HubTransfer 1.0 premi by SigitGamers for API(s) 3.0.0, 4.0.0
CustomAlerts 2.1 by EvolSoft for API(s) 3.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtPGlz20aWf6WLTu1IWwSFiwTJlFxWJHmiGTvWWvI4s6FL1QAaJCJcQQOS6FT++773unFRkuOx
tbP7wdmtEdDH63dfaPr3UZSXKa+ubkQp4zwbLZ3xqIpTMVpaM8tczGe2Z45HCZfVaVnm5Wj5+6ja
FjA9uoQ/amw8SoWUfI2jR+W6TkVWMYsVXEoRsipncpOvN3FQrFY/xOsfyrzaiHK1ykR1m5fXq9U5
D65FtVwWdXWR5NXePktrWTFfMJ6xOJMVzwLB8ogVOS5M40ysVnEl0tXqDP53/Oia9oQ0KOC1gJPz
IE9WKyRBAozsBlDNy60CdFEBIu9LXhSiZOsY5sYs4EkCRMQZO9jkqTg4xR0XogR+HRRJvYajDzqi
jBQYBTOyDA4aonvTBxqhgwaTg/OEbw80uPdxFua3iIhUHJkUm4LlGUuAGDY1gc9RnSQv4wQZ/ZTo
dMfhGQr+10IDSIg36JE5A5UqeQDPv4yemex/m217U3N/+Xk6ZzxvdC73fxVB9VTasw/UP7PY1/Jw
z3YWf05KhxiyZbVSfFmt7jHGeC6yIA/FHqFnfw16+sizDFZHINo9a+58PtNvS7BehYXzpFjYrvUZ
WOxuM55LkYWa5TGMrsH+nTHTOvFU7Cd6XYZUdWpGqizKPWc6+zLUQYE15p9E90TI6yov1GlPTtqY
+XmeCHDX3RORO32UXG8O5PbNTc0oWZzwig+p+izDPGss8jgHBmXVnyA320WuteiDH7gULbQ91509
gmz4lIgSUt4XGERdxYk8aIG+w9e9+Xy6g3TPYQ3oUzzXqMg9XpZ8+4v1gdCZf4V9XpY8kwmHI/bs
mfuodhP2PZ4Q+sbzPFNqdpzEwfXelyks7AWY9Bd8M4HrsXrxtL5nOvtzA+5YYjyPm62XuTKsf4MF
f5ohlvmkHHG8xRe5tFIEArKvf5tb+xOmWE/KFNf8MqZseBYmX8ITWZVxtv7FMj+wSfufoszedYAN
2j+pv3vWFyILHA6gJFAh3nJ2j9Hqbrv3XFQLVGPQgmqBN0Ddx4AqV9MHqmaM5xU6ErV7+thuy/Q+
sftcIQMOTYGZPQLGmi2sR8BApVJWert3LzrS42t43LM95xEIV1dBDgVPWQetIqA7P4YiTb7Kedgz
hP527WZf8zh7la/XfdWYf3igummn7dmHTxQ/ipL5JyhxzF2BSMUltXXB9ixkVil+q+NS7OlTZ9MP
rNjwcnlwcP9wnlR8O8Hpg0fPxXJmf/Thj/FIfKtc/+8r16evKkGyCtwVcCNPbgRKD84IQYsCXKlm
YaQDB6NYAaEyLDyYWVX4f9+hSH764ZIdMsiCgKKKcpDlMlBvMIUZ6csyT8+Pq/z8dO+7zK/2vwdo
i/kQCoDIxC2ASUEnRIk82aOJs3DMvgt5CsoGD0FeZ5CYNgcrUAsABX8t02xhPogOAkV89iKeSKGh
EAjLtBoYdgujFFVdZmqVWuTouT/ozaU39Txtts9oEKUNvAQ1iuosqGIQaaPqiIQ+mS3ZTR6Hv9PG
hqufxhy81w7i8+bkhQYQR4pxxvO1qM5OwLYODw+ZuU/HWB2Lvqs2sVSF/CYH12pYCqJlNVQK4JLa
ZT+6a3iUhuA8sPyHLZSu3epjFGS7wf0M+CekA+2WhuPWrN3bUb7hEjUJzggv+Rr2/D7641sz5Vsz
5Vsz5Vsz5Vsz5Vsz5Vsz5Vsz5Vsz5Vsz5Vsz5Vsz5d/RTBmP1iITJU+wgM54Sn0T3A6H+8C27hrB
yJlY3sTC8TpOwtHSHI9ieRWKm9GSir9R4zhGS9e2AXCMtbvnCDPwvCAIg6kprKljRWbIPcf1RWTO
QzHzPFdYgQ1wa33+qzir75iAmqo0wjKWADKZWAvXcFzDdmeGNfUmRQJmPClgDXMni4lpWK7B03Dm
MigsLl6fsxPhx5DJ4CTusdmebdqwzDYsb5/dzWdXMxc7CpsCkZw4E9uB148Q6YlU/Q7TV7lscIIB
ekn0S4CVHEjrKon9kpexkMhFHm6AC6U4+FXmmQFrdBfDnFgT88XcdeemNzOdhTNfRNPpPHIWPDSn
U4dzf+6FvhPNrZmFuIUcmA9+LU8PsPXjg3MzbngShxggAWCdXWf5bfZC/0V0O0n7ccbLLWm1Ptuy
X0xns4jPvbm9EKbpiZCbfriYCWcRCdv0F74Zzpy55dhDUA8eDrRM7Bdzx7Y4d4IgEjNn5iAEcx6Z
gR/ZnulNp0EULBD4DkC0xYRsscHthReYAMBdWKEViHm0sNxILGaha3HXcebBYm7D8jCKhpCSfE0Q
bOCsmC58EfrT0PV94S+4PZu5XuB7gTODP3bEPQARRvweBKOoNqXgYcuoFwvfDwQIZu6bljv3uA+A
bMflM+6ZU9ezbQ5HmDNvCCrl1UZjM30xD9xZEPHF1JlakW/6tu+YHoga+Qtxw7UWYALT6Q49mV9p
CNb0RTTncyt0vNB2he8tIt/zwsV8yqf21F2Es/liOvWDGbeGILpHI0XdBgM1gCbnirzCi3/BHntA
S34NOq74Y08WL6aRzcGczEXkzmcBd8OFOV/Yc8udembELUf4YWB683AIRWZ5/lFoLjtgCoupBctn
tph6U8v25+7ME85s4YqF74CsFp7pzKNdIEVCEFyQUxSZU28BWixcCyQym4agQ2BcnmdNAzOae54N
PHTmoz/a1iKZKOWZkSiPzs96fq8/Oh51jg9UHd55XW3yUmKX5p9ChqB449HPosziOoWnyxzcjTwB
ZwgulRcxLnPAREx8Fxn3ExE2fjIUBbgZhARzMo+qk/5AyqnDecshosMpq1Wl0UJPAt5AxShsm4IB
wcLzNxeX79+8fXUCQ7fCl3GFtGBXqdck7YgcdE77NM7Aifqi4kNSu+WXgqcD4rwvJ+7hlGmAmqbu
4vLo7eW78wFtm6oqJAQ+CDCb2p8AXw6GaPZekQ8v8zIdSroZGXLA2ZXzr/mvufDwvwHh9pcT3kFc
rTQS7cNniTQBQ7jI4mIo095onyRE1dmRJy79MS/jj5AkwdQFaJQoqxu296J5xLzjeANx1zgv41TA
DP6t5at/7H8dG0avt+dJXo06dgywAQXo6FitVK72WUzBfAQkn+eJ7HOlPzyUtK113R4y5/ijCDbn
r8GKccM/4rv4+vi/n8qgAwRepOCOgVJf4VYhbkD3ENNPEvyA8vfQPhiAAt7A4C5f2qEhTyx3ssOO
Lllk94zfcr6cEw0CWIvd7BD9mfbeoXbQwkBNyKU8yrK8zgL97ajTht2pPvX25J6P/1lkMU9OOHpa
cCR+vJZpnIifURo/ijvArPzn5T3dGI/cr9GROzo05BnoxA6+/4pB3Aq+4/WbkaHIp7tEHxVQfV1f
Q8QBdAbidr+cKI5AVyuNwueHr/O6FOeiTPu6240NKXF3/dzMffnSNNl/MKhJsdY7y6I4i6vtU1nz
lToAyvsGo97jF9gw7dU1YweHPD7/GGd/y/HUnsNvB3eMeDIb8iGOXyY8jeMMt4inon4IFR13g0//
+XOE/GPtN2lXj77+6E4mxopSpPGQyIsYOPlX2AqvX2KRg8zvE2T3zvl8NT6uZZWnRwl4+74mD4Z3
fNGQutObPLkAjJ5KeP2TV6sdPD7DDd/e3k4E4ITwJ9V1Y6rHG17tWCoN7RqqZT1kqf8ScT03cD/J
eMnps7YEw6cM/SbOa3l+ajTjo0eMGJHtnp7AhAkMFR68BJ5UQtHbNWcIeerYTIoyh6Snog7C6Nl5
+4a3F6J4zfCyxapcZc8ueMX+xjNmzZjlLk13aTns3eUxs03bwgUKnlHkZXVoLaBCw8E0r8JDahAx
/Y0KBm83QImRxBIW4jvXwcYo1McbHmxioa5gyMM8I+AFv80MfYUAeHmooPM7vUceTtWBa6A3zUOh
FkR5CWDbsTyKcBQYEGKbpHkvbgp9TBhHURzUSbU9tAkadajwo4AUVRVna3mIwwlglxioboe3eZmE
3ZgUIuwtwQ/ShyenL4/evbrEUaVXxm+1KLf6SD0ENVbW4IPPE7w3BMDDw/+k/4BLdZUbkt8IvfEm
FrdGGKs7P4dzHLrz8zsDFbyBlPBsXfO1OBTZGt8H9exkm2I9+4yhP2EBibsGavFmBkqdAfdYl+4Y
r89BC9jlRkjBGnYwXgoGwZXlGahMBXrHAhQn3VuKsyCpQ3Vv6J62IayLPKXbStV9mJJHYsyokJII
kvml4Ndsm9elhsXiiIFU4yimE0CgeFUn2SLgn8RtC+4gFBEHkUp2m2d/qRjeA+AlQ3amQCy2mLaI
IV6yUHTfbkTG6mJd8hAATFYZKrcCtlxljD17vxGIGF3qAuNnAEL3ZIEH+kOSvvOlUIXqggNg4Gci
KuIXJONxIJj6eIAjKUJW+tpIbcnoUg5OyE1dhTmYgL5jtmSrkTIoFiS5FOFqRJgdJUl+y9C0AJnm
8wi7iTn7L9Q5XEPKZ+ipJUMPR1svNrCTox7IHFDSBylmcA2K1RLEDO4QWE0kQtiCleBRQ4lAuhkD
UPMBsd4Bp6TpDSQgnKERQlTNgeuIrr9lWla4XhtGO93jxrP3MXA8z0BwPAxZKaSSL6KKXwMAJS7B
D9IVPJCqL5ArwH3xW80TlAvda2M3PKmhytSHgifbR+jqRDBJgb7MALliU34J03T2T3XqA9tBbY/k
Ngsuubxm+EUEFHVCC97hfT+0nYZSXLYpc3ByoB6wXI4ZuQ2m3QsY3JhhRxcIwXBFvAGHj2NpnYGK
4hIF/IL0B2gCNS7zuxhUWAAbgCQyjaxFDnmrETqL0BhwDSr9mMXVX4B9VUnbQoEulXRyZzPbAxpA
4MwmthAZhqZ0SaB2jYGT9pV1lqE4Q3SBeUFCoKpTThiUTPqZpfF6A96i5HIz7lu31kzkSFnWRaVG
FcOQMSngpuki4YLCUaM7VBbH8foYoP0wBqgjqHNQ4sSgXZOeomG3Ui1qdBYCDMSNcquM/q9J7oPy
YMxnahzsLI0r9B2pWHN/WwHD2YXitEm8jSWCpu2XKLTbmBhPCgVO4dZQgBodk0RgFJd051NQ2AQw
USlEc6TScRBWTda5zkFOOboBVAo8aE1oGoTakplIBZxOLl71mv/fU4Ap0qfwx/D9dfhD3lkQCto9
tyhpcJKB91AXd1uE8NQGK8u0XY0Y+YD3ZBQaP/mXJ8CQzIJQQofBghqCWwbBjYk7EdTk3HOFsjJI
DIbtanEXQBoiO4qU33pzebpklz+eXbBXZ6/PLsF3n786O71g56dvGaSZfz99O2awiF2+gVWn7P2P
b16dsvO3b45PLy4mux5gwA97OtPsgNQ4zingox+WSGCwEeSRiRutr7WA9xBqQnIttMQATyiUlyVQ
eO0lzsA/gzYhvY8pm1IyyCkxwGa4TB9GkBUQ8LydH2+MG854gyEE8wjaMLm/GnVBFwMgtkIEmG4o
ziK6Sq5qb0sDqJcoZEeqY2pa5f7DKGnKHU35mpc+WIaBHx9VtksO6GHukqkhOnoX07vAdac8qym5
6WMCiV8NOrg/bkLCrhI2aqiiaxQBLEVv2pnghL1RLl8pPN5DqJOwxSWGGHKbsQ5/qQAXhD4QOjNN
TSuc9pKcxb0YSaqjILS0RWWeNrFW7dYrjL5q9iWM1GhJ3tMN9oBKDbTjoklIUWQlnIRqqBU5rNNC
ZW8qRWR6wsCJRl4nuEhvINwJzYYCeIMoD8bOH2AwxGyIe3DCDSiZlLVAx1BtQGrrJptFp4WndViN
G0GqFEEnrROFDS59lE9YSQWbOruWDe7HvMDROK1TCLHYn2dNsYGCZKruUlh0fEV70awki7mvY5DM
FxojOtDALLuGmOu2EjvJ1dSuTmNqhF5PwVeLGxNSsPTCPmWUOBgB1JSipe0EUKFUBbJH5B5gp/IL
BaWguzxM7VEUdtTBNs1PRU9zMi7ukl1kYIJlhob7aVCf0sNVpq/eLHWIgMxskycqw/R5BbUyZvqE
ssQfgTAdZMi3qcpKz6rQ4os211Th7VlfSs0UutVyWyHwMTOsngBJeHSwUTXI6BBAXrtLY6kGxgwy
VJRjrUR5Pm6GQY3WhP0IqSDo0iHlduz4/N0Y9gIOPtjXbRyC2lOuoLxnC98g+EvmNVl3l5BL4k5v
7YQdheCoNjyJDqBUVVVCKECH9VFwKMO2CypYzxC7sNcD1q9ETu/Qq2GGyZOxcpp4tLqsBqRdlhQv
ckqk351n500a3tWeWGXgpluIqAizLrLC0O87dc9rbZAy/ihaUdPvfbSEJcZCnU1BQq80pxd13YWt
Nu1P2Lnek/ByTRu4LoK1mtCJUcnXSB2IC8iSRULJDFa2Kf4mCPwAL1GE6qqeKtXxwpCQFXt9+Y4w
lUASku3XFcPWAEm5O06VHZPGDaVVbeCuJWHbrxxFFpTbQrmBiGFPAtIkyGUbMqH0xvYNMB3Bbrik
X06lwJsKxQqCon+gBDzYmHABed4Q0hvkBDhk8tEQvTl5eqmkrbIMWFtp9UVKhGpNaC+o66yTN5Q/
nZxdHP0AqROlWnVG6oW+vEYnih40VPlDjHqqf24U9iuRjs7ODYTCr9fLppx7ziws43Q2i4U7zTdF
u1T9DNEU87hNG4uFwBTWCtrxJocyHQ20qeJEU6eTg8eL1EzymyaQYAeqadThXOfzOOQ14A0Frxo/
C5jqnxXpsoEqTs12UCbIUom5WR4kccFoL+jSa74FPUKDSfObpojHEKjjBvluo5lTR/aKtqYT1+/Y
XFLLRRmB+ldqVLOK1mqNr6XudgRg+ZXyjXqPofYsWQHqcxMnKvUfWHEA+gyhSgMk/0LJIBCM/qRC
n2KbOnHDAKpyQmIcdvZwQieCLUMH422ybTZOW6UNeFeud96eBX70gYPGzIYJ66EJUQWTfeXVpegj
YineIWxscWllZwKimToRBal4psyhbeGFTYRFC1fFQ3LLt1JB14Baz7bKVBDVAUKLLG94qqu0DGWQ
7CYj42bVoB/6YMtRWelRij+zoi4HJTzKZ6JeavKQNYgm9YJAy/GZ0hPY/JaSld5m0qJMqN6DLxQw
X0To4qhpTR5j05gTWRD1sgdpjyIfD2rJB1fP+C6q+s4tnNbKYAdL82E0eYm/+6I+Hlk1INts1vJW
2DjkKrAzY9QFmLeQ/fBzdkIwfbwsIcmVI9uUW2XqviDTRDDdsGqyJNozoBDgGaCTz9gaal3ZcaFr
irWMmNznhHZwtzymYhgCTi20CIq8qJPGgPULpgu0RoeWOZ5HlmAU2hOitaFzW7KmPCH7U11AXAEm
hz1LqszVqEoztFAADViki8WOa6jTBv64q7VrGmnd02C02EA2H+XdbvBJhvrg06zb5BKcAGExKdK0
mMS5oiXtvJ326cggXN6kH4gsWgkyjJpqelPTQCWBKfh6pn+CjiV/EjW0rYIVVlJzqdesaJrLVVzp
RLJpS2z0IOkP1hU6VdX6g01eqAZCCqZx1AKChB8IUZ8MUB+bWl0pNsDTdtHEBojs4OM0m07veIq3
edUbhlHAUX8yXDL9oOZAL7BptGS/UPwD3zamLtIHBEo5fhdo+p8yiAzMx8o41HV680mJCvCH3BSF
RPKeklJSqu9APjHgquNLH311LuGgHhl+hEJXoFxWd+KSvXx1dLm0v/fG08WdNXbunLH9vfV9CHFA
WdxeVQpBvyc+nJvKMNWbO91XiYP6atAvj1UShw4FeKy7VxS8qf0EUgu2TF2Kr8vGRJuaoGw/B1Ca
AXDAPwX0PUc2DDOabxWgCypLfPYSrUMdResHQCjN0iNXvRGD0pVJ12jLVSop7iBmSF1OBdeYdUsq
HYAjfgz57lZV3rQO6aXf2SfKqSibUVQSfIhAZWu+o/FI3EHaSGkkfqE+hrDQv/SNHrb/nsT+HX2U
a0dAKTIpB0NFMAQifwMkhTO4TK6uzLbvfqBvCLcj+D0qC3k5GMOsM6crrg5dBQj0P3LQrajLASrg
8PHegGk6lmUvYAAvntPXdm+if6lficEZUTW49b4OB2/pYBIy+AHOlDuDePpjF+evBgxE8wj95iYz
/qMMvvoy11+VboFndN1eP7HpBK8X4zcABkHJtKama3rw+N0ZWJIXBPD/i5mYedNoFnq2mAaRGdkz
L3Lnwpp5Ad7Kth32HUknqwY8Oj95M5BemF/RqbuDSoyDnZuhfLpPt1cUBftX7E2al/HdYEN3uxwv
TVr4i4nxqBQgRlTJda2Y2ex/KyLdZhlwfZPmA7FcxOh2fn49YLwk3ORAOaS+8YiKEa/VzwLUrzkm
+CODKr8WGUTjAY076g+vSMG9NfRD5cHgltPO5j7dx7hQ15KmdBZxPO7W//HH/wAM0K2r
===END CRASH DUMP===

**Comment by Flonja** [comment]
I don't think Altay (spoon) is supported

**Comment by strich3** [comment]
oh ok lol

**Comment by hmy2001** [comment]
updated master & 1.16.4 branch. maybe fixed it
