### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GlacierShard92** [BigBrotherTeam/BigBrother#19]
- Would plugins impact the connection of PC players to the server?
- Also, I'm hosting my server on my own machine. Would that affect players joining too?
 - Last, what MCPC version is allowed to join?

**Comment by Driesboy** [comment]
ALL PLUGINS WILL WORK,
yes
1.11.2

**Comment by SuperMaXAleX** [comment]
BigBrother can't even modify chunks and modify the server comportement. It's a plugin. It's just 'converter' for MCPC to MCPE.
