### ISSUE TITLE
Player get kicked, Player Cant respawn

### ISSUE THREAD

**Issue by erkam2002** [BigBrotherTeam/BigBrother#20]
CRITICAL> [Netzwerk] Schnittstelle shoghicp\BigBrother\network\ProtocolInterface wurde wegen Return value of pocketmine\item\Item::parseCompoundTag() must be an instance of pocketmine\nbt\tag\CompoundTag, instance of pocketmine\nbt\tag\EndTag returned beendet
[Tesseract] [11:49:52] EMERGENCY> [ServerThread #139998059820800] ServerThread crashed!

-------------------

**Comment by hmy2001** [comment]
fix

**Comment by erkam2002** [comment]
If player hit a pe player with an arrow will he kicked
