### ISSUE TITLE
implement conversion for transfer

### ISSUE THREAD

**Issue by Driesboy** [BigBrotherTeam/BigBrother#24]

**Comment by hmy2001** [comment]
Minecraft: PC has no transfer packet

**Comment by Driesboy** [comment]
how servers like cubecraft do that than?

Op 21-mrt.-2017 07:03 schreef "hmy2001" <notifications@github.com>:

**Comment by hmy2001** [comment]
I don't know

**Comment by Driesboy** [comment]
Bungeecord

Op 21-mrt.-2017 07:25 schreef "hmy2001" <notifications@github.com>:
