### ISSUE TITLE
Can not pick-up items/blocks on the floor/chest.

### ISSUE THREAD

**Issue by Driesboy** [BigBrotherTeam/BigBrother#25]

**Comment by SuperMaXAleX** [comment]
Do a description please.
It will be better for the presentation.

**Comment by NextGenDan** [comment]
When breaking a block, the item can't be picked up. As well, items flash momentarily before going invisible.

**Comment by hmy2001** [comment]
@NextGenDan Thank you for reporting to me it, fixed it
