### ISSUE TITLE
Problem with parseCompoundTag().

### ISSUE THREAD

**Issue by SuperMaXAleX** [BigBrotherTeam/BigBrother#29]
Spawn/be around an entity will kick the PC Player from the server.
CRITICAL> [Network] Stopped interface shoghicp\BigBrother\network\ProtocolInterface due to Return value of pocketmine\item\Item::parseCompoundTag() must be an instance of pocketmine\nbt\tag\CompoundTag, instance of pocketmine\nbt\tag\EndTag returned

And the ServerThread will crash.
EMERGENCY> [ServerThread] ServerThread crashed!

**Comment by hmy2001** [comment]
I don't know when it will occur

**Comment by hmy2001** [comment]
I will fix it.

**Comment by hmy2001** [comment]
Hmm. is there still problem now?

**Comment by SuperMaXAleX** [comment]
I’ll try right now

**Comment by SuperMaXAleX** [comment]
Seems to be fixed
