### ISSUE TITLE
you can break corps

### ISSUE THREAD

**Issue by Driesboy** [BigBrotherTeam/BigBrother#30]
disable break block event 
picture is coming soon

**Comment by hmy2001** [comment]
What did you put up this Issue for?

**Comment by hmy2001** [comment]
crops?

**Comment by Driesboy** [comment]
plants

**Comment by hmy2001** [comment]
i don't have it. You have that problem?

**Comment by Driesboy** [comment]
on 24 mart yes

**Comment by Driesboy** [comment]
did not test it yet
