### ISSUE TITLE
Can't join

### ISSUE THREAD

**Issue by MalakasPlayzMC** [BigBrotherTeam/BigBrother#31]
When I try to log into my server from PC I get the message: Disconnected

Info:

Server version: 1.0.4
Server software: Tesseract
Minecraft PC version: 1.11.2

**Comment by Driesboy** [comment]
it works for me

**Comment by MalakasPlayzMC** [comment]
Sorry my fault, I had not port forwarded the port 25565.

**Comment by Driesboy** [comment]
close plz

**Comment by MalakasPlayzMC** [comment]
Now I get the message: Login Timeout

**Comment by MalakasPlayzMC** [comment]
The only plugin I have in my server is BigBrother

**Comment by Driesboy** [comment]
i dont have that bug

**Comment by MalakasPlayzMC** [comment]
What do I do wrong?

**Comment by MalakasPlayzMC** [comment]
I host my server from the PocketServer app

**Comment by Driesboy** [comment]
not enougt ram or something like this

**Comment by MalakasPlayzMC** [comment]
Ok, where could I host my server to make the plugin to work? I don't have enough space to my PC so I can't host my server there

**Comment by poustmal** [comment]
[Receive][Interface] 0x00
LoginStart
[Send][Interface] 0x00
[Tesseract] [18:33:31] INFO> [/193.92.63.232:9364] logged out due to Login timeout
[Receive][Interface] 0x00
LoginStart
[Send][Interface] 0x00
[Tesseract] [18:33:52] INFO> [/193.92.63.232:9371] logged out due to Login timeout

**Comment by hmy2001** [comment]
#8
