### ISSUE TITLE
 future suport for pmmp

### ISSUE THREAD

**Issue by caspervanneck** [BigBrotherTeam/BigBrother#36]
https://github.com/pmmp/PocketMine-MP/tree/api3/network-mcpe-1.1/src/pocketmine/network/mcpe

the folder has change and i dont know if Tesseract will change this 
if so we need  remove pmmp suport   ): so plz help @AppleDevelops @hmy2001

**Comment by AppleDevelops** [comment]
I guess I'll update Tesseract for more support

**Comment by caspervanneck** [comment]
@AppleDevelops thnx

**Comment by hmy2001** [comment]
I want support only Tesseract.

**Comment by AppleDevelops** [comment]
@hmy2001 We'll get more people to use this with multi-software support.

**Comment by caspervanneck** [comment]
@hmy2001  only suport Tesseract its.

 already working on Tesseract

**Comment by poustmal** [comment]
Someone or owner discontinued tesseract.see the issues there..........

**Comment by poustmal** [comment]
Some people made a fork of it,but I think that you should make this plugin support pmmp..

**Comment by caspervanneck** [comment]
@poustmal  yes i know

**Comment by hmy2001** [comment]
Pmmp has changed incompatible, so I will not support it

**Comment by caspervanneck** [comment]
okey
