### ISSUE TITLE
console spam, + timeout

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [BigBrotherTeam/BigBrother#38]
At first I could join, but after I chat, console spam
send interface : some numbers, and then just spam, and if I try to join it timed out!

Big brother is a good idea btw, but not usable.

**Comment by poustmal** [comment]
Maybe your internet connection is bad,or plugin has problem that I believe

**Comment by DelxHQ** [comment]
The number spam is the packets being sent and received from the MCPC client

**Comment by caspervanneck** [comment]
your not use right software
