### ISSUE TITLE
TCP internet protocol?

### ISSUE THREAD

**Issue by poustmal** [BigBrotherTeam/BigBrother#39]
Can support this for mcpc?if its possible.Also,if its yes,may solve the login timeout problem I think

**Comment by caspervanneck** [comment]
@poustmal login timeout is software based so

**Comment by caspervanneck** [comment]
Its tcp i tink and why do need it any way

**Comment by poustmal** [comment]
I think my friend's wifi can't connect mcpe even with mcpe app,but can join on mcpc servers.idk
