### ISSUE TITLE
enderchest crash server and block breeking

### ISSUE THREAD

**Issue by caspervanneck** [BigBrotherTeam/BigBrother#40]

**Comment by caspervanneck** [comment]
14:16:03││Server thread│CRITICAL > [Network] Stopped interface shoghicp\BigBrother\network\ProtocolInterface due to Call to undefined method shoghicp\BigBrother\DesktopPlayer::allowInstaBreak()
14:16:03││Server thread│EMERGENCY > [ServerThread #3896] ServerThread crashed!

**Comment by hmy2001** [comment]
I think that problem of Server Software

**Comment by caspervanneck** [comment]
i test enderchest with Tesseract

**Comment by hmy2001** [comment]
You must test with mcpe

**Comment by caspervanneck** [comment]
okey

**Comment by caspervanneck** [comment]
enderchest is working on mcpe so

**Comment by hmy2001** [comment]
oh no

**Comment by caspervanneck** [comment]
blockbreeking is server software

**Comment by hmy2001** [comment]
I tested it but don't have it

**Comment by caspervanneck** [comment]
okey
