### ISSUE TITLE
Server thread crash after joining

### ISSUE THREAD

**Issue by ImKyd** [BigBrotherTeam/BigBrother#41]
I get this after joining
[ServerThread #139942996997888] ServerThread crashed!

**Comment by ImKyd** [comment]
Oh, I updated to latest tesseract now I join and then it kick and say this:
![image](https://user-images.githubusercontent.com/26284839/27001448-a1e24440-4dca-11e7-89c0-728e0abc2590.png)

**Comment by hmy2001** [comment]
I don't have it :(

**Comment by hmy2001** [comment]
Please give me your Tesseract Data

**Comment by ImKyd** [comment]
I removed file where is stored player data and it working

**Comment by hmy2001** [comment]
understand
