### ISSUE TITLE
Can't join from PC

### ISSUE THREAD

**Issue by MalakasPlayzMC** [BigBrotherTeam/BigBrother#44]
I can't join from PC! In the console in says

> [Receive][Interface] 0x00
> LoginStart
> [Tesseract] [16:00:50] [INFO] [/192.168.1.102:62808] logged out due to Connection closed

In the game I get the message: Timed out

Information:
My server is running Tesseract-1.3.0 Unity
PHP version: 7.0.13
API: 3.0.1
Target client: Minecraft PE v1.1.0.55
Protocol version: 113
Minecraft PC version: 1.12

**Comment by hmy2001** [comment]
plz give me Tesseract Data

**Comment by MalakasPlayzMC** [comment]
Ok
https://github.com/CookieSoftware/Tesseract
I have modified all the network/mcpe/protocol/... to network/protocol/...
And all ProtocolInfo to Info

**Comment by hmy2001** [comment]
This plugin isn't support old path
please use network\mcpe\protocol\....

**Comment by MalakasPlayzMC** [comment]
Yes, but Tesseract has the path /network/protocol/...

**Comment by hmy2001** [comment]
use pmmp or use rewrite tool with tesseract

**Comment by caspervanneck** [comment]
you ken use spigotpe

its hase more blocks and more

**Comment by caspervanneck** [comment]
@MalakasPlayzMC

**Comment by MalakasPlayzMC** [comment]
Can you tell me one rewrite tool?

**Comment by caspervanneck** [comment]
https://github.com/spigotpe-beta/Spigotpe

**Comment by MalakasPlayzMC** [comment]
Is SpigotPE written in php?

**Comment by caspervanneck** [comment]
no not really but you can use spigotpe

**Comment by caspervanneck** [comment]
yes php

**Comment by MalakasPlayzMC** [comment]
Ok wait...

**Comment by MalakasPlayzMC** [comment]
![screenshot_2017-06-16-16-49-52](https://user-images.githubusercontent.com/26123354/27229376-0c659658-52b4-11e7-8327-746357cd7661.png)

**Comment by caspervanneck** [comment]
o wow android hosting i cant test it on android

**Comment by MalakasPlayzMC** [comment]
Just use PocketServer

**Comment by hmy2001** [comment]
Maybe, Please reopen it if it is not fixed.

**Comment by MalakasPlayzMC** [comment]
I can't re-open it if you close it. Plus, in the description you say that it supports Tesseract. Can you send me a link of Tessseract?

**Comment by hmy2001** [comment]
No

**Comment by hmy2001** [comment]
My application development environment is pmmp/PocketMine-MP
