### ISSUE TITLE
Login timed out when I logged in from PC with default skin

### ISSUE THREAD

**Issue by eternalharvest** [BigBrotherTeam/BigBrother#46]
### Prerequisite
* PocketMine-MP (pmmp version from pmmp.io)
  https://pmmp.io/ (maybe 1.6.2dev-3.0.0-ALPHA6)
  https://github.com/pmmp/PocketMine-MP/releases/tag/1.6.2dev-3.0.0-ALPHA6
* Minecraft PC Vanilla version 1.12
* BigBrother plugin (BigBrotherTeam/BigBrother master branch 265442b8de74a341620f82b78535a8f82d636eb5)

### How to reproduce
* Reset skin to default on the profile page of minecraft.net
  https://minecraft.net/profile/
* Login to the PocketMine-MP server from PC version of minecraft.
* Login failed with the following error message

```
Connection Lost
Login timeout
```

### 
I'm new to PocketMine-MP and BigBrother plugin.
So, I'm not sure whether this behavior is a bug or just my configuration is wrong.
I made sure that I can login from PC version of minecraft if I upload skin on the profile page of minecraft.net.

Thank you for developping such a nice plugin (bit buggy though).

### Screenshot
<img width="1025" alt="pocketmine" src="https://user-images.githubusercontent.com/1128403/27592618-e06d08f8-5b8f-11e7-91e5-930b85ce4f21.png">

### Server log
```
[22:25:29] [Server thread/INFO]: [/10.1.100.32:51692] logged out due to Login timeout
[22:26:51] [Server thread/INFO]: [/10.1.100.32:51706] logged out due to Login timeout
```

**Comment by hmy2001** [comment]
Thank you for reporting that problem. That proble fixed by @6dd11df
