### ISSUE TITLE
PC user can't move after killed by command

### ISSUE THREAD

**Issue by eternalharvest** [BigBrotherTeam/BigBrother#51]
### Issue description
I'm not sure whether if this is a really BigBrother bug.
But it seems that any PE user is no problem.

### Prerequisite
* pmmp (branch api3\blocks b6014c222895450b5e3e8306932ac5dcda62fec4)
* BigBrother (branch master b59f6c523368dda741c8738a159840f71a04b71f)
* MineCraft PC Edition v1.12

### How to reproduce
* Login with PC client
* Kill PC user by self (suicide) or, PC user is killed by another user who has 'op' privileges.
* Click "Respawn" button
* "Respawn" button is still displaying there
* Click "Respawn" again

PC user can't move any more.

### Server log(crash dump)
no server log related to this issue.

**Comment by caspervanneck** [comment]
its working for me and am using myb own pmmp fork

**Comment by eternalharvest** [comment]
thank u for quick reply!
u mean that u are working on it?

**Comment by caspervanneck** [comment]
no respawning is working for me but some time it dont work

**Comment by caspervanneck** [comment]
so yes your right 

sorry for my bad eng

**Comment by caspervanneck** [comment]
am going to fix it soon or let @hmy2001 do the work

**Comment by caspervanneck** [comment]
he or she is very fast :P

**Comment by eternalharvest** [comment]
don't mind, my english is not so good too.
thank you!

**Comment by eternalharvest** [comment]
I notice that i can't reproduce this issue with master branch of pmmp `70bd9af`.
So, I think this is not issue ralated to BigBrother plugin.
