### ISSUE TITLE
I can't join from my PC to server

### ISSUE THREAD

**Issue by Dominis7Hubowy** [BigBrotherTeam/BigBrother#55]
When joining to server console says
![console](https://user-images.githubusercontent.com/29919178/27868380-d4c13534-619c-11e7-950a-379041c91f55.png)

And in minecraft see this

![mc](https://user-images.githubusercontent.com/29919178/27868421-eb0449ee-619c-11e7-9038-1d141a40c517.png)

And can you give me a pmmp engine compatible with bigbrother ?

**Comment by eternalharvest** [comment]
Is it reproduceable?
Have you tries to restart your client?
Please describe more specific info!

**Comment by Dominis7Hubowy** [comment]
I'm restart my client. And when join to server in console see "Login Timeout" Can you give me a tested PocketMine engine ?

**Comment by eternalharvest** [comment]
How to give you PocketMine engine?
upload phar files?

**Comment by Dominis7Hubowy** [comment]
Yes

**Comment by eternalharvest** [comment]
I do'nt care giving phar file to you, but u have to identify the issue so that any other people in here can understand and fix it.
This is not support forum...

**Comment by Dominis7Hubowy** [comment]
Oh. Ok
