### ISSUE TITLE
Collision's problem with dropped item

### ISSUE THREAD

**Issue by SuperMaXAleX** [BigBrotherTeam/BigBrother#59]
### Issue description
Dropped item disappears when it collides with a block.

### Prerequisite
Tested with other plugins and not. Just try to install BigBrother, join with MC:Java Edition – drop an item – and see the issue.

### How to reproduce
When you are dropping an item and when it collides with a block, it will disappear in this block (-1).
If this block, where there is the dropped item, is broken, we can see the item disappear again on the another block who was below it.
I'm sure – It's a collision's problem.

**Comment by eternalharvest** [comment]
I know it from while ago.
But i'm not debug it yet...
Can u fix it?

**Comment by SuperMaXAleX** [comment]
I'll try

**Comment by eternalharvest** [comment]
I noticed that if i trigger the TNT block explosion with flint and steel, the TNT block dive into the ground.
In addition, block which is broken by TNT seems not updated correctly.
Is it related to this issue?

**Comment by eternalharvest** [comment]
I debugged this issue, and found a solution which may solve this.
It also fix the problem about PrimedTNT entity.
