### ISSUE TITLE
crash agian

### ISSUE THREAD

**Issue by caspervanneck** [BigBrotherTeam/BigBrother#6]
[Tesseract] [16:30:39] CRITICAL> TypeError: "Argument 1 passed to shoghicp\BigBrother\utils\Binary::writeMetadata() must be of the type array, null given, called in C:\Users\Wesle\Desktop\mcpe server\plugins\BigBrother-master\src\shoghicp\BigBrother\network\protocol\Play\SpawnMobPacket.php on line 56" (EXCEPTION) in "/plugins/BigBrother-master/src/shoghicp/BigBrother/utils/Binary" at line 96
[Tesseract] [16:30:39] EMERGENCY> An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Tesseract] [16:30:39] EMERGENCY> Please upload the "C:\Users\Wesle\Desktop\mcpe server\crashdumps/CrashDump_Tue_Feb_21-16.30.39-UTC_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

Tesseract Crash Dump Tue Feb 21 16:30:39 UTC 2017

Error: Argument 1 passed to shoghicp\BigBrother\utils\Binary::writeMetadata() must be of the type array, null given, called in C:\Users\Wesle\Desktop\mcpe server\plugins\BigBrother-master\src\shoghicp\BigBrother\network\protocol\Play\SpawnMobPacket.php on line 56
File: /plugins/BigBrother-master/src/shoghicp/BigBrother/utils/Binary
Line: 96
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN : BigBrother v1.6.0-beta

Code:
[87] 				//TODO: add data type
[88] 			}
[89] 		}
[90] 
[91] 		$newdata["convert"] = true;
[92] 
[93] 		return $newdata;
[94] 	}
[95] 
[96] 	public static function writeMetadata(array $data){
[97] 		if(!isset($data["convert"])){
[98] 			$data = self::convertPEToPCMetadata($data);
[99] 		}
[100] 
[101] 		$m = "";
[102] 
[103] 		foreach($data as $bottom => $d){
[104] 			if($bottom === "convert"){
[105] 				continue;
[106] 			}

Backtrace:
#0 /plugins/BigBrother-master/src/shoghicp/BigBrother/network/Packet(202): shoghicp\BigBrother\network\protocol\Play\SpawnMobPacket->encode(boolean)
#1 /plugins/BigBrother-master/src/shoghicp/BigBrother/network/ProtocolInterface(125): shoghicp\BigBrother\network\Packet->write(boolean)
#2 /plugins/BigBrother-master/src/shoghicp/BigBrother/network/ProtocolInterface(163): shoghicp\BigBrother\network\ProtocolInterface->sendPacket(integer 2, shoghicp\BigBrother\network\protocol\Play\SpawnMobPacket object)
#3 /src/pocketmine/Player(1083): shoghicp\BigBrother\network\ProtocolInterface->putPacket(shoghicp\BigBrother\DesktopPlayer DesktopPlayer(1), shoghicp\BigBrother\network\protocol\Play\SpawnMobPacket object, boolean , boolean )
#4 /src/pocketmine/entity/Item(237): pocketmine\Player->dataPacket(pocketmine\network\protocol\AddItemEntityPacket object)
#5 /src/pocketmine/entity/Entity(1810): pocketmine\entity\Item->spawnTo(shoghicp\BigBrother\DesktopPlayer DesktopPlayer(1))
#6 /src/pocketmine/level/format/Chunk(719): pocketmine\entity\Entity->spawnToAll(boolean)
#7 /src/pocketmine/level/Level(2719): pocketmine\level\format\Chunk->initChunk(boolean)
#8 /src/pocketmine/level/Level(2299): pocketmine\level\Level->loadChunk(integer 20, integer 10, boolean 1)
#9 /src/pocketmine/level/Level(2970): pocketmine\level\Level->getChunk(integer 20, integer 10, boolean 1)
#10 /plugins/BigBrother-master/src/shoghicp/BigBrother/DesktopPlayer(176): pocketmine\level\Level->populateChunk(integer 20, integer 10)
#11 /src/pocketmine/Player(1799): shoghicp\BigBrother\DesktopPlayer->sendNextChunk(boolean)
#12 /src/pocketmine/Server(2652): pocketmine\Player->checkNetwork(boolean)
#13 /src/pocketmine/Server(2370): pocketmine\Server->tick(boolean)
#14 /src/pocketmine/Server(2280): pocketmine\Server->tickProcessor(boolean)
#15 /src/pocketmine/Server(1841): pocketmine\Server->start(boolean)
#16 /src/pocketmine/PocketMine(469): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Wesle\Desktop\mcpe server\, string C:\Users\Wesle\Desktop\mcpe server\, string C:\Users\Wesle\Desktop\mcpe server\plugins\, string unknown)

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 101; API 3.0.0]
uname -a: Windows NT DESKTOP-G72R5H7 10.0 build 14393 (Windows 10) AMD64
PHP version: 7.0.13
Zend version: 3.0.0
OS : WINNT, win

Server uptime: 17 seconds
Number of loaded worlds: 1
Players online: 1/20

Loaded plugins:
DevTools 1.11.1 by PocketMine Team for API(s) 2.0.0, 3.0.0-ALPHA3
JamAuth 0.4.php by JamAuth for API(s) 3.0.0, 3.0.0-ALPHA3
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 3.0.0-ALPHA3, 3.0.0-ALPHA2
FactionsPro 1.3.7.AWZ by Tethered_ & Awzaw for API(s) 2.0.0, 3.0.0-ALPHA3
LiveTexts 1.4pre by EmreTr1 for API(s) 3.0.0-ALPHA3, 2.0.0
PurePerms 1.4.0-INDEV by 64FF00 & ProjectInfinity for API(s) 1.13.0, 3.0.0-ALPHA3
SignPortal 1.1.2 by 99leonchang for API(s) 3.0.0-ALPHA3
iProtector 3.1b by LDX for API(s) 3.0.0-ALPHA3
BigBrother 1.6.0-beta by shoghicp for API(s) 3.0.0, 3.0.0-ALPHA3
PureChat 1.4.6 by 64FF00 for API(s) 1.13.0, 3.0.0-ALPHA3

**Comment by hmy2001** [comment]
fixed it
