### ISSUE TITLE
The player is invisible when there is a MC:Java's player.

### ISSUE THREAD

**Issue by SuperMaXAleX** [BigBrotherTeam/BigBrother#60]
### Issue description
This issue is making a player invisible when there is an another one.

### Pre-requisite
* Last PMMP version
* a PE (or Java) player
* a Java player 

### How to reproduce
This is happening when a player (of any versions) is joining a server & there is already a MC:Java's player on this server, the player who joined will be invisible for every MC:Java's players.
Conversely, if there is already a connected player on the server and a MC:Java's player is joining it, he will see every players.

**Comment by eternalharvest** [comment]
I tested with two PC (Java) client and one PE (iPhone SE), but it seems anybody can see eachother...

**Comment by SuperMaXAleX** [comment]
That's what I said on this issue, yep

**Comment by eternalharvest** [comment]
???

**Comment by hmy2001** [comment]
Is there still a problem now?
