### ISSUE TITLE
Trapdoor block can not be closed by any PC user

### ISSUE THREAD

**Issue by eternalharvest** [BigBrotherTeam/BigBrother#64]
### Issue description
Trapdoor block can not be closed by any PC user, but PE user can open/close trapdoor.
I'm not debugged this issue yet. But I think this issue may affect any other block.

### Prerequisite
* PocketMine-MP `g8bb0c53`
* BigBrother master branch 76b03ad

### How to reproduce
* Place Trapdoor block
* Right click the placed Trapdoor block

### Server log(crash dump)
no server log related to this issue.

**Comment by eternalharvest** [comment]
Stupid Mojang!!
According to the following link, It seems 0x04 is the correct mask of OPENED state flag in PC edition.

http://minecraft.gamepedia.com/Trapdoor

But, in PMMP code-base it seems 0x08 is the mask of OPENED state flag.
https://github.com/pmmp/PocketMine-MP/blob/1a7f567a70c58b0848def59118aad16557750ff3/src/pocketmine/block/Trapdoor.php#L34

I think there are more issue that we are not noticed....

**Comment by hmy2001** [comment]
Hmm, We need implement convert block damage on ConvertUtils

**Comment by eternalharvest** [comment]
Yes, u are right.
I wrote a change-set to solve this problem. I will create a pull-request soon.
