### ISSUE TITLE
PC user can't break soft block (block with hardness 0) though PE user can

### ISSUE THREAD

**Issue by eternalharvest** [BigBrotherTeam/BigBrother#67]
### Issue description
I found that some block which does not drop any item when PC user break the block. It seems that this issue is related on block hardness. PC client does not send `PayerDiggingPacket` with the state `ACTION_STOP_BREAK` when PC user broke the block which hardness is 0. So, PMMP doesn't remove block on the server, and doesn't drop anything.

If PE user observe this case, the block is shown as the state it is not broken (no changes). I confirmed this scenario with block (Torch and Redstone-torch).

And if PC user try to place new block on the same place, block placement is cancelled and the original block which PC user tried to break is appear again. Or if PC user logged-out and logged-in again the server, there is a block which PC user tried to break.

### Prerequisite
* PocketMine-MP `g8bb0c53`
* BigBrother 4f680f9147e10be05936f2ff0b65deb31522422a
* Minecraft PC Java Edition 1.12
* Minecraft PE v1.1.3 (iOS on iPhone SE)

### How to reproduce
* PE user and PC user logged-in the same server
* Place a Torch block (or Redstone block or, something so on...)
* Observe PC user's behaviour by PE client
* Try to break the block by PC client

### Server log(crash dump)
* no server log related to this issue.

**Comment by eternalharvest** [comment]
I'm not sure why these strange thing happens, but it seems PC client do not send a `PayerDiggingPacket` with the state `ACTION_STOP_BREAK` when PC user break some block such as Torch, Redstone-Torch, Instead PC client send `PlayerDiggingPacket` with the state `ACTION_ABORT_BREAK`.

hmm...

**Comment by hmy2001** [comment]
Hmm, I tested it problem. but, I could not reproduce it
