### ISSUE TITLE
There is a mistake when I try to enter

### ISSUE THREAD

**Issue by alair069** [BigBrotherTeam/BigBrother#70]
![image](https://user-images.githubusercontent.com/27539870/28996041-4f40b16a-79ce-11e7-87ac-801ab8a8f48e.png)

**Comment by SuperMaXAleX** [comment]
What plugins have you on your server ?

**Comment by hmy2001** [comment]
Plz give me Server Data

**Comment by Driesboy** [comment]
i have this error with some worlds idk why cause they are imported from mcpc

**Comment by alair069** [comment]
![image](https://user-images.githubusercontent.com/27539870/28996356-440a7a40-79d5-11e7-97f6-40793bf21a57.png)
These are the plugins I have on the server

**Comment by Driesboy** [comment]
what is murder??

**Comment by alair069** [comment]
A minigame

**Comment by Driesboy** [comment]
murder mystery??

**Comment by SuperMaXAleX** [comment]
@alair069 This can be caused due to MapImageEngine or/and Murder

**Comment by hmy2001** [comment]
maybe fixed it.

You must test it

**Comment by alair069** [comment]
It worked Thanks
