### ISSUE TITLE
Error: fieldsize is too long!

### ISSUE THREAD

**Issue by AbelGamerC** [BigBrotherTeam/BigBrother#71]
Hello, when I log into minecraft 1.12 I get an error in the game and it says: "fieldsize is too long !, Length is 2560, but maximium is 112"

**Comment by Driesboy** [comment]
wow an exact replica

**Comment by hmy2001** [comment]
Plz write about problem

**Comment by AbelGamerC** [comment]
![captura](https://user-images.githubusercontent.com/15161559/28996685-ca7cac3e-79ca-11e7-91c9-27e295394457.PNG)

**Comment by hmy2001** [comment]
plz give world data

**Comment by AbelGamerC** [comment]
[lobby3.zip](https://github.com/BigBrotherTeam/BigBrother/files/1202492/lobby3.zip)

**Comment by hmy2001** [comment]
thank you
That world is used for only debug.

**Comment by AbelGamerC** [comment]
lol

**Comment by AbelGamerC** [comment]
console log:
![captura](https://user-images.githubusercontent.com/15161559/28996841-f1d36dc0-79cc-11e7-8415-671be8b3fe56.PNG)

**Comment by Driesboy** [comment]
pro editing skills

**Comment by AbelGamerC** [comment]
XD, How can I solve this problem???

**Comment by hmy2001** [comment]
maybe fixed it.

You must test it
