### ISSUE TITLE
Its impossible to join from mcpc

### ISSUE THREAD

**Issue by poustmal** [BigBrotherTeam/BigBrother#74]
Pmmp version: https://github.com/pmmp/PocketMine-MP/commit/b9c4a653073aeb5c3cfefc77a21ab9abd5427ec2
Bigbrother version: 501a295
My friend had tried to join and on console sometimes it was saying login timeout and other times connection closed and I was using bigbrother without plugins.

**Comment by hmy2001** [comment]
Thank you for reporting it.
Can you  give me Server data?
