### ISSUE TITLE
Class contains abstract method and must therefore be declared abstract

### ISSUE THREAD

**Issue by thelucyclub** [BigBrotherTeam/BigBrother#75]
### Issue description
Fatal error: Class shoghicp\BigBrother\network\ProtocolInterface contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (pocketmine\network\SourceInterface::start) in C:\Users\sebas_000\Desktop\PocketMine-MP-master\plugins\BigBrother-master\src\shoghicp\BigBrother\network\ProtocolInterface.php on line 69
### How to reproduce
Run on PMMP 1.6.2-dev579

**Comment by hmy2001** [comment]
Thank you for reporting it!
Fix it!
