### ISSUE TITLE
CRASH, can not start

### ISSUE THREAD

**Issue by GarryLai** [BigBrotherTeam/BigBrother#76]
### Issue description

CRASH, can not start

### How to reproduce

Display on starting

### Server log(crash dump)
ParseError: "syntax error, unexpected '?', expecting variable (T_VARIABLE)" (EXCEPTION) in "/plugins/BigBrother-master/src/shoghicp/BigBrother/BigBrother" at line 252

**Comment by SuperMaXAleX** [comment]
Update your PHP binary to 7.2. Thanks.
