### ISSUE TITLE
Fail to join !

### ISSUE THREAD

**Issue by iTCMega** [BigBrotherTeam/BigBrother#8]
22.02 06:48:15 [Server] Server thread/INFO logged out due to Login timeout
22.02 06:48:15 [Server] INFO [Send][Interface] 0x00
22.02 06:48:15 [Server] INFO }
22.02 06:48:15 [Server] INFO string(13) "Login timeout"
22.02 06:48:15 [Server] INFO ["text"]=>
22.02 06:48:15 [Server] INFO array(1) {
22.02 06:48:05 [Server] INFO LoginStart

**Comment by hmy2001** [comment]
Are you use last version?

**Comment by kabluinc** [comment]
yep I'm using latest version to but it says:

LoginStart
array(1) {
  ["text"]=>
  string(13) "Login timeout"
}
[Send][Interface] 0x00
[13:29:22] [Server thread/INFO]: [/192.168.0.10:63023] logged out due to Login timeout

**Comment by caspervanneck** [comment]
i gone try it

**Comment by caspervanneck** [comment]
@hmy2001 its working for me

**Comment by caspervanneck** [comment]
@iTCMega its your auth plugin

**Comment by kabluinc** [comment]
Tried with no plugins still not working. I'm using PMMP 1.6.2 for MCPE 1.0.3 and connecting using 1.11.2. Only plugins installed are devtools and bigbrother

**Comment by poustmal** [comment]
I have this problem,too and I'm using the latest version.I downloaded immediately when I found new update.

**Comment by Driesboy** [comment]
im using tesseract and its working

**Comment by poustmal** [comment]
I'm using genisys elywing.

**Comment by kabluinc** [comment]
Tried on tessaract to.. still same issue. Which MCPC version are you using @Driesboy

**Comment by caspervanneck** [comment]
@kabluinc i now to a Login timeout

**Comment by iTCMega** [comment]
i use lastest pmmp still not working!

@caspervanneck nope im not using any auth plugin

**Comment by iTCMega** [comment]
@hmy2001 yep

**Comment by hmy2001** [comment]
I think that server is slowly

**Comment by SuperMaXAleX** [comment]
Re-try again, please.

**Comment by Driesboy** [comment]
I will test in a few min

**Comment by hmy2001** [comment]
fixed it?

**Comment by Driesboy** [comment]
i dont have this bug

**Comment by caspervanneck** [comment]
well its you software
