### ISSUE TITLE
Error Syntax

### ISSUE THREAD

**Issue by alair069** [BigBrotherTeam/BigBrother#84]
[Server thread/CRITICAL]: ParseError: "syntax error, unexpected '?', expecting variable (T_VARIABLE)" (EXCEPTION) in "plugins/BigBrother-master/src/shoghicp/BigBrother/BigBrother" at line 258
 [Server thread/CRITICAL]: Could not load plugin 'BigBrother'

**Comment by hmy2001** [comment]
Please use php7.2 binary!

**Comment by eternalharvest** [comment]
dupplicate issue #76
