### ISSUE TITLE
the pitch of MineCraft PE Edition's player seems wrong...

### ISSUE THREAD

**Issue by eternalharvest** [BigBrotherTeam/BigBrother#87]
### Issue description
the above titled issue...

### Prerequisite
* PHP 7.2.0RC3
```
PHP 7.2.0RC3 (cli) (built: Oct 11 2017 23:27:25) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies
```
* PMMP master branch https://github.com/pmmp/PocketMine-MP/commit/15d6fd86e2b221686865a1838e11cdab243cf084
* BigBrother latest master branch 47c3da52d78ca8261802e9d0eb218cbc67edc8d7

### How to reproduce
* Player A login with Minecraft PE edition
* Player B login with Minecraft PC edition
* Observe player A's head from view of B
* Player A look sky or ground

### Server log(crash dump)
no server log related to this issue

**Comment by hmy2001** [comment]
Fixed by https://github.com/BigBrotherTeam/BigBrother/commit/4afa0884085bb6bc52db2b32318cdc4b4e697731
