### ISSUE TITLE
i cant craft or get items

### ISSUE THREAD

**Issue by caspervanneck** [BigBrotherTeam/BigBrother#9]
plz can you make it

**Comment by caspervanneck** [comment]
and cant grieve

**Comment by Driesboy** [comment]
is that a problem? i hate greafers

**Comment by caspervanneck** [comment]
No I use factiona do pearls can't get any items

**Comment by SuperMaXAleX** [comment]
Please, report bugs, don't suggest us what we need to add. We know what we need to do and on what we need to work. We are adding new functionalitys when majors bugs are fixed.

**Comment by caspervanneck** [comment]
@SuperMaXAleX it is a bug you cant get any item

**Comment by caspervanneck** [comment]
zo reopen
