### ISSUE TITLE
Invalid Skin Disconnection

### ISSUE THREAD

**Issue by AlexCreeper25** [BigBrotherTeam/BigBrother#90]
Using the Latest plugin vesrion, i tried to join from MCPC 1.12.2, everything went well but during the connection I got kicked for disconnectionScreen.InvalidSkin

Log String:[17:06:37] [Server thread/INFO]: AlexCreeper25[/---------] logged out due to Invalid skin!

There's no crashdump...
Thank you for helping!

**Comment by eternalharvest** [comment]
Though i'm not confirmed this issue yet, i think it's because size of `LoginPacket::clientData['SkindData']` is wrong...
Please confirm whether if this issue reproduces when u reset ur skin from the following link.

https://minecraft.net/profile

And please describe the PMMP version u are using!

**Comment by AlexCreeper25** [comment]
ok, im using PMMP 1.7-dev API 3.0.0-ALPHA 8 (ALPHA 9 said incompatible API version) and yes, also if I have the default skin the issue persists
Thank you for your quick support!

**Comment by AlexCreeper25** [comment]
anyone?

**Comment by eternalharvest** [comment]
Please use latest **master** branch of BigBrother and PMMP!!
Currently, BigBrother supports "3.0.0-ALPHA9" only.

**Comment by AlexCreeper25** [comment]
Ok, but, when i compile a phar for PMMP 1.7 3.0.0-ALPHA9 it says Incompatible API version. Btw, I'll try again...

**Comment by hmy2001** [comment]
@AlexCreeper25 Where did you get phar from?
