### ISSUE TITLE
getXuid() returning null

### ISSUE THREAD

**Issue by SuperMaXAleX** [BigBrotherTeam/BigBrother#91]
### Issue description
The title says everything.
Joining a server will crash because of this error.

### How to reproduce
- Your server on online mode, or not, this bug is happening every joining
- A MC:PC Player
- Join your server
That's it

### Server log(crash dump)
```
[Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerLoginEvent' to 'Core v2': Return value of pocketmine\Player::getXuid() must be of the type string, null returned on core\Core
[Server thread/CRITICAL]: TypeError: "Return value of pocketmine\Player::getXuid() must be of the type string, null returned" (EXCEPTION) in "src/pocketmine/Player" at line 359
```
We need to set to the PC player a valid Xuid.

**Comment by hmy2001** [comment]
This issue is fixed by returning crc32 encoded username.
