### ISSUE TITLE
VarInt too big

### ISSUE THREAD

**Issue by SuperMaXAleX** [BigBrotherTeam/BigBrother#92]
### Issue description
When a player joins and there are plugins on the server, the player can be disconnected with this message : 
![error](https://user-images.githubusercontent.com/19352571/32293797-9536bb9a-bf44-11e7-909e-1ba0d12ee923.png)
The player is kicked for `Connection closed`.

### How to reproduce
I think it's coming from some packets who I'm using on my server like AddPlayerPacket, MovePlayerPacket. I suppose. I'm not sure.

### Server log(crash dump)
There is nothing. But, after debugging, I found this issue is coming from here : 
```
[448]	}elseif($pid === ServerManager::PACKET_CLOSE_SESSION){
[449]		$id = Binary::readInt(substr($buffer, $offset, 4));
[450]		$offset += 4;
[451]		$flag = Binary::readInt(substr($buffer, $offset, 4));
[452]
[453]		if(isset($this->sessionsPlayers[$id])){
[454]			if($flag === 0){
[455]				$this->close($this->sessionsPlayers[$id]);
[456]			}else{
[457]				$this->closeSession($id); 
[458]			}
[459]		}
[460]	}
```

**Comment by hmy2001** [comment]
I think that eid is than int

**Comment by SuperMaXAleX** [comment]
@hmy2001 You think it's something to do with the entityRuntimeId ?

**Comment by SuperMaXAleX** [comment]
Confirmed. It has something to do with AddPlayerPacket and AddEntityPacket. I tried many different ids, but nothing change, same error.

**Comment by hmy2001** [comment]
yes

really?
What do you use ids?

**Comment by SuperMaXAleX** [comment]
If the id is bigger than ~100, it kicks the PC player.

**Comment by hmy2001** [comment]
I don't have its problem.....

**Comment by hmy2001** [comment]
Can you open the server?

**Comment by SuperMaXAleX** [comment]
yep

**Comment by hmy2001** [comment]
added its problem to todo list as clean-up network code
