### ISSUE TITLE
Colors are totally wrong with ChatPacket

### ISSUE THREAD

**Issue by SuperMaXAleX** [BigBrotherTeam/BigBrother#93]
### Issue description
Colors are totally wrong with `Player->sendPopup()`, `Player->sendTip()` and `Player->addActionBarMessage()` only. (messages work fine)
-  `Player->sendPopup()` doesn't send colors, everything is white.
-  `Player->sendTip()` is mixing every colors, it doesn't give the correct one.
-  `Player->addActionBarMessage()`, this one is totally random, it can give correct colors and repeat the text in white, or give the wrong colors.

**I'll do more research today. Wait before fixing anything.**

### How to reproduce
Just use these who has been said on the issue description.

### Server log(crash dump)
None.

**Comment by hmy2001** [comment]
See [MC-119145](https://bugs.mojang.com/browse/MC-119145) for more information.

**Comment by hmy2001** [comment]
I can fix it

**Comment by SuperMaXAleX** [comment]
@hmy2001 So Action bar is glitched ? A hack is necessary ?

**Comment by hmy2001** [comment]
Yes.
I want to commit for fix

**Comment by hmy2001** [comment]
i think that i fixed it

**Comment by SuperMaXAleX** [comment]
@hmy2001 Colors are back but the `TextFormat::BOLD` is doing this : 
![capture d ecran 2017-11-04 a 11 04 58](https://user-images.githubusercontent.com/19352571/32404471-6e09ec82-c150-11e7-8a0d-d536d0bbc281.png)
It adds 2 times the text and do not add the **bold**.
After a `var_dump` of `$result = json_encode($result, JSON_UNESCAPED_SLASHES)` on **BigBrother.php** at the line **317**, I got this : 
```
string(235) "{"bold":true,"color":"yellow","text":"\u00a7l\u00a7e- \u00a7cINSTANTS\u00a76BRAIN \u00a7e-","extra":[{"color":"red","bold":true,"text":"INSTANTS"},{"color":"gold","bold":true,"text":"BRAIN "},{"color":"yellow","bold":true,"text":"-"}]}"
```

Here is the original one text : 
```
string(32) "§l§e- §cINSTANTS§6BRAIN §e-"
```

Oh, and `\n` is replaced by a weird character : 
![capture d ecran 2017-11-04 a 11 04 37](https://user-images.githubusercontent.com/19352571/32404459-31923a66-c150-11e7-9612-222b3d093080.png)

**Comment by hmy2001** [comment]
i think we cannot use bold

**Comment by hmy2001** [comment]
also, we cannot use "\n"

**Comment by SuperMaXAleX** [comment]
Oh, didn't know that, it's pretty sad. :/

**Comment by hmy2001** [comment]
so, We must use TitlePacket

**Comment by SuperMaXAleX** [comment]
Fixed !
