### ISSUE TITLE
Server crash and connection closed

### ISSUE THREAD

**Issue by kabluinc** [BigBrotherTeam/BigBrother#98]
### Issue description
Hi, the last issue where the server crashed was solved however there is a new issue and the server crashes. Crashdump below

### Server log(crash dump)
`PocketMine-MP Crash Dump Fri Dec 22 18:31:43 UTC 2017

Error: Undefined variable: playerdata
File: plugins/BigBrother-master/src/shoghicp/BigBrother/network/Translator
Line: 2240
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BigBrother v1.6.0-beta

Code:
[2231] 					case 0://Add
[2232] 						$pk->actionID = PlayerListPacket::TYPE_ADD;
[2233] 
[2234] 						$loggedInPlayers = $player->getServer()->getLoggedInPlayers();
[2235] 						foreach($packet->entries as $entry){
[2236] 							if(isset($loggedInPlayers[$entry->uuid->toBinary()])){
[2237] 								$playerdata = $loggedInPlayers[$entry->uuid->toBinary()];
[2238] 							}
[2239] 
[2240] 							if($playerdata instanceof DesktopPlayer){
[2241] 								$properties = $playerdata->bigBrother_getProperties();
[2242] 							}else{
[2243] 								//TODO: Skin Problem
[2244] 								$value = [//Dummy Data
[2245] 									"timestamp" => 0,
[2246] 									"profileId" => str_replace("-", "", $entry->uuid->toString()),
[2247] 									"profileName" => TextFormat::clean($entry->username),
[2248] 									"textures" => [
[2249] 										"SKIN" => [
[2250] 											//TODO

Backtrace:
#0 plugins/BigBrother-master/src/shoghicp/BigBrother/network/Translator(2240): pocketmine\error_handler(integer 8, string Undefined variable: playerdata, string /home/vdesktop/test/plugins/BigBrother-master/src/shoghicp/BigBrother/network/Translator.php, integer 2240, array Array())
#1 plugins/BigBrother-master/src/shoghicp/BigBrother/network/Translator(2390): shoghicp\BigBrother\network\Translator->serverToInterface(shoghicp\BigBrother\DesktopPlayer object, pocketmine\network\mcpe\protocol\PlayerListPacket object)
#2 plugins/BigBrother-master/src/shoghicp/BigBrother/network/ProtocolInterface(240): shoghicp\BigBrother\network\Translator->serverToInterface(shoghicp\BigBrother\DesktopPlayer object, pocketmine\network\mcpe\protocol\BatchPacket object)
#3 src/pocketmine/Player(3036): shoghicp\BigBrother\network\ProtocolInterface->putPacket(shoghicp\BigBrother\DesktopPlayer object, pocketmine\network\mcpe\protocol\BatchPacket object, boolean , boolean )
#4 src/pocketmine/Server(1928): pocketmine\Player->sendDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object, boolean , boolean )
#5 src/pocketmine/Server(1914): pocketmine\Server->broadcastPacketsCallback(pocketmine\network\mcpe\protocol\BatchPacket object, array Array(), boolean )
#6 src/pocketmine/Server(1875): pocketmine\Server->batchPackets(array Array(), array Array(), boolean )
#7 src/pocketmine/Server(2334): pocketmine\Server->broadcastPacket(array Array(), pocketmine\network\mcpe\protocol\PlayerListPacket object)
#8 plugins/Slapper-master/src/slapper/entities/SlapperHuman(63): pocketmine\Server->updatePlayerListData(pocketmine\utils\UUID object, integer 12, string ..4PEZ, pocketmine\entity\Skin object, array Array())
#9 src/pocketmine/entity/Entity(1885): slapper\entities\SlapperHuman->sendSpawnPacket(shoghicp\BigBrother\DesktopPlayer object)
#10 src/pocketmine/entity/Human(529): pocketmine\entity\Entity->spawnTo(shoghicp\BigBrother\DesktopPlayer object)
#11 src/pocketmine/Player(996): pocketmine\entity\Human->spawnTo(shoghicp\BigBrother\DesktopPlayer object)
#12 src/pocketmine/Player(931): pocketmine\Player->doFirstSpawn()
#13 plugins/BigBrother-master/src/shoghicp/BigBrother/DesktopPlayer(374): pocketmine\Player->sendChunk(integer -4, integer 3, pocketmine\network\mcpe\protocol\BatchPacket object)
#14 src/pocketmine/level/Level(2523): shoghicp\BigBrother\DesktopPlayer->sendChunk(integer -4, integer 3, pocketmine\network\mcpe\protocol\BatchPacket object)
#15 src/pocketmine/level/Level(2564): pocketmine\level\Level->sendChunkFromCache(integer -4, integer 3)
#16 src/pocketmine/level/format/io/ChunkRequestTask(88): pocketmine\level\Level->chunkRequestCallback(integer -4, integer 3, pocketmine\network\mcpe\protocol\BatchPacket object)
#17 src/pocketmine/scheduler/AsyncPool(164): pocketmine\level\format\io\ChunkRequestTask->onCompletion(pocketmine\Server object)
#18 src/pocketmine/scheduler/ServerScheduler(342): pocketmine\scheduler\AsyncPool->collectTasks()
#19 src/pocketmine/Server(2531): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 11655)
#20 src/pocketmine/Server(2274): pocketmine\Server->tick()
#21 src/pocketmine/Server(2149): pocketmine\Server->tickProcessor()
#22 src/pocketmine/Server(1737): pocketmine\Server->start()
#23 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/vdesktop/test/, string /home/vdesktop/test/plugins/)

PocketMine-MP version: 1.7dev #0 [Protocol 160; API 3.0.0-ALPHA10]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux test 3.13.0-132-generic #181-Ubuntu SMP Wed Sep 13 13:25:03 UTC 2017 x86_64
PHP Version: 7.2.0
Zend version: 3.2.0
OS : Linux, linux`

**Comment by hmy2001** [comment]
Fixed it.
