### ISSUE TITLE
Another crash

### ISSUE THREAD

**Issue by kabluinc** [BigBrotherTeam/BigBrother#99]
### Issue description
Hi, I'm really sorry to keep opening new issues. But now I'm getting a new crash from the latest version. Crashdump below. Thanks allot.

### Server log(crash dump)
`PocketMine-MP Crash Dump Sat Dec 23 18:29:00 UTC 2017

Error: Call to a member function getGamemode() on null
File: plugins/BigBrother-master/src/shoghicp/BigBrother/network/Translator
Line: 2268
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BigBrother v1.6.0-beta

Code:
[2259] 										"value" => base64_encode(json_encode($value)),
[2260] 									]
[2261] 								];
[2262] 							}
[2263] 
[2264] 							$pk->players[] = [
[2265] 								$entry->uuid->toBinary(),
[2266] 								TextFormat::clean($entry->username),
[2267] 								$properties,
[2268] 								$playerdata->getGamemode(),
[2269] 								0,
[2270] 								true,
[2271] 								BigBrother::toJSON($entry->username)
[2272] 							];
[2273] 						}
[2274] 					break;
[2275] 					case 1://Remove
[2276] 						$pk->actionID = PlayerListPacket::TYPE_REMOVE;
[2277] 
[2278] 						foreach($packet->entries as $entry){

Backtrace:
#0 plugins/BigBrother-master/src/shoghicp/BigBrother/network/Translator(2391): shoghicp\BigBrother\network\Translator->serverToInterface(shoghicp\BigBrother\DesktopPlayer object, pocketmine\network\mcpe\protocol\PlayerListPacket object)
#1 plugins/BigBrother-master/src/shoghicp/BigBrother/network/ProtocolInterface(240): shoghicp\BigBrother\network\Translator->serverToInterface(shoghicp\BigBrother\DesktopPlayer object, pocketmine\network\mcpe\protocol\BatchPacket object)
#2 src/pocketmine/Player(3036): shoghicp\BigBrother\network\ProtocolInterface->putPacket(shoghicp\BigBrother\DesktopPlayer object, pocketmine\network\mcpe\protocol\BatchPacket object, boolean , boolean )
#3 src/pocketmine/Server(1928): pocketmine\Player->sendDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object, boolean , boolean )
#4 src/pocketmine/Server(1914): pocketmine\Server->broadcastPacketsCallback(pocketmine\network\mcpe\protocol\BatchPacket object, array Array(), boolean )
#5 src/pocketmine/Server(1875): pocketmine\Server->batchPackets(array Array(), array Array(), boolean )
#6 src/pocketmine/Server(2334): pocketmine\Server->broadcastPacket(array Array(), pocketmine\network\mcpe\protocol\PlayerListPacket object)
#7 plugins/Slapper-master/src/slapper/entities/SlapperHuman(63): pocketmine\Server->updatePlayerListData(pocketmine\utils\UUID object, integer 12, string ..4PEZ, pocketmine\entity\Skin object, array Array())
#8 src/pocketmine/entity/Entity(1885): slapper\entities\SlapperHuman->sendSpawnPacket(shoghicp\BigBrother\DesktopPlayer object)
#9 src/pocketmine/entity/Human(529): pocketmine\entity\Entity->spawnTo(shoghicp\BigBrother\DesktopPlayer object)
#10 src/pocketmine/Player(996): pocketmine\entity\Human->spawnTo(shoghicp\BigBrother\DesktopPlayer object)
#11 src/pocketmine/Player(931): pocketmine\Player->doFirstSpawn()
#12 plugins/BigBrother-master/src/shoghicp/BigBrother/DesktopPlayer(374): pocketmine\Player->sendChunk(integer -7, integer 10, pocketmine\network\mcpe\protocol\BatchPacket object)
#13 src/pocketmine/level/Level(2523): shoghicp\BigBrother\DesktopPlayer->sendChunk(integer -7, integer 10, pocketmine\network\mcpe\protocol\BatchPacket object)
#14 src/pocketmine/level/Level(2564): pocketmine\level\Level->sendChunkFromCache(integer -7, integer 10)
#15 src/pocketmine/level/format/io/ChunkRequestTask(88): pocketmine\level\Level->chunkRequestCallback(integer -7, integer 10, pocketmine\network\mcpe\protocol\BatchPacket object)
#16 src/pocketmine/scheduler/AsyncPool(164): pocketmine\level\format\io\ChunkRequestTask->onCompletion(pocketmine\Server object)
#17 src/pocketmine/scheduler/ServerScheduler(342): pocketmine\scheduler\AsyncPool->collectTasks()
#18 src/pocketmine/Server(2531): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 160)
#19 src/pocketmine/Server(2274): pocketmine\Server->tick()
#20 src/pocketmine/Server(2149): pocketmine\Server->tickProcessor()
#21 src/pocketmine/Server(1737): pocketmine\Server->start()
#22 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/vdesktop/test/, string /home/vdesktop/test/plugins/)

PocketMine-MP version: 1.7dev #0 [Protocol 160; API 3.0.0-ALPHA10]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux test 3.13.0-132-generic #181-Ubuntu SMP Wed Sep 13 13:25:03 UTC 2017 x86_64
PHP Version: 7.2.0
Zend version: 3.2.0
OS : Linux, linux
`

**Comment by hmy2001** [comment]
I'm sorry.....

**Comment by kabluinc** [comment]
No problem. Appreciate your effort to fix these things :)

**Comment by hmy2001** [comment]
Fixed it!!!!!!!

**Comment by kabluinc** [comment]
Thanks!! when joining in clean new worlds the player can connect fine. but in some worlds I crash insantly and it shows connection closed in console and this in client.

[https://imgur.com/a/feWZ1](url)
